### ISSUE TITLE
Require portals to have frames made of certain materials

### ISSUE THREAD

**Issue by gmcnew** [Multiverse/Multiverse-Portals#127]
Some server operators (read: me) might not like the fact that Multiverse portals are extremely cheap and easy to build -- any material will work. This can impact:
- **difficulty**: If you're trapped or lost in a dark cave, instead of having to find a way out, you can simply make a portal, warp to your base, deposit your loot, and never return to the cave again.
- **aesthetics**: It's nice for portals to look similar, and frames made of random materials aren't conducive to that.

One solution would be to require that portal frames be made out of certain materials.

**I will be happy to write a patch for this.** Right now I just want some feedback on how it might work. =)

The config file would have a new option -- say, "framematerials" -- which would either be (a) "any" (the default) or (b) a space-delimited list of block IDs to consider valid frame materials. For a frame to be valid, all of its blocks must have the same block ID, and that block ID must be in the framematerials list.

For performance reasons, the frame would only be examined when the portal is created and when the portal is used. (This means a portal's frame could be altered to contain incorrect materials after it was created, but the portal would not work -- players would receive a message instead of teleporting.) Like nether portals in vanilla Minecraft, the corner blocks on frames would be optional.

Thoughts?

**Comment by benwoo1110** [comment]
This is an available feature, not sure why the issue is still open.
