### ISSUE TITLE
Blocks Go through Portals

### ISSUE THREAD

**Issue by TrueHelp** [Multiverse/Multiverse-Portals#168]
When people press Q and throw a block, it will put the block in the world the other side of that portal. Not helpful when you have a creative world and a survival world

**Comment by Jadiction** [comment]
I know this is a very old post, but I wasn't able to do this anymore. So I'm going to close the ticket. Please open a new ticket if this issue persists or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
