### ISSUE TITLE
Feature Request: Random Destination on Target World

### ISSUE THREAD

**Issue by Pwn9** [Multiverse/Multiverse-Portals#175]
Would it be possible to make a portal drop players within a random rage of areas on the destination world.  Perhaps this would require a new destination type..  

/mvtp r:worldname:x1,y1,z1:x2,y2,z2  

where R stands for random and the coordinate set is a 2 point rectangle of the coordinates in which you could randomly spawn.

**Comment by FernFerret** [comment]
Not a random destination, but close!

https://github.com/Multiverse/Multiverse-Portals/commits/master/src/main/java/com/onarandombox/MultiversePortals/destination/RandomPortalDestination.java

Random portals are supported.

Random destination on target world will have to takes some params, as we don't want to put someone in a place that would generate chunks or maybe we do...

**Comment by FernFerret** [comment]
If you're still interested in this, it would fall under [Multiverse-Core](https://github.com/Multiverse/Multiverse-Core/issues). Please reopen it there.
