### ISSUE TITLE
How To Not Keep Inven

### ISSUE THREAD

**Issue by Speakmore** [Multiverse/Multiverse-Portals#194]
Hey all,
Just a quick question I hope I can get an answer to. I downloaded multiverse today and was making portals, now for my server we are going to have a zone for Donars only. The world is creative, they will make whatever they want on their land or plot, so on and so forth. However, inventories transfer over from the regular world to creative then creative back.
How can I get it so that the inventory can swap between only a few worlds... Or just in general not this world.
If someone could help me out with that, I'd be grateful
Thanks,
Speakmore

**Comment by FernFerret** [comment]
You should check out [Multiverse Inventories](https://github.com/Multiverse/Multiverse-Inventories) Multiverse Core and portals do not support this.
