### ISSUE TITLE
add this

### ISSUE THREAD

**Issue by ci29995** [Multiverse/Multiverse-Portals#197]
Hello, I am a World Portal user and I LOVE how I can simply teleport by pressing a button instead of walking into an ugly over-sized portal. But the thing is, this plugin does not restrict users from using specific portals with permissions, from what I know, only Multiverse does this, but then Multiverse has huge ugly portals you walk into.

All I want is a plugin that restrict user groups/ranks from using specific portals with permissions, and also have the portal as a simple small button.

This would be the absolute perfect portal plugin ever made!

World Portal: http://dev.bukkit.org/server-mods/world-portal/
Multiverse-Portals: http://dev.bukkit.org/server-mods/multiverse-portals/

**Comment by FernFerret** [comment]
Hi, i'm not sure what you mean by your feature request. If you're still interested in this (yes I realize It's been 3 years) please reopen this issue! I'm going around and closing issues to clean up the issue tracker.
