### ISSUE TITLE
Issues with telenonplayers (parent task)

### ISSUE THREAD

**Issue by sthycb** [Multiverse/Multiverse-Portals#200]
Creating a parent task for my future pull request to fix the multitude of  telenonplayers issues that have been reported:

MV-Core Issue #913 (moved to MV-P Issue #201 )
MV-P Issue #184 Tamed wolves and cats not following through portals - Feature request 
MV-P Issue #183 Chunks Don't Load When Going From world to world_nether by Minecart
MV-P Issue #148 World doesn't load when going through portal in minecart 
MV-P Issue #115 teleportnonplayers
MV-P Issue #168 Blocks Go through Portals

MV-P Request #185 Feature Suggestion: Portal Direction (When no Specific direction is set in the config)

and Undocumented Issues:

Railcraft/mv-P: issue where railcraft carts respawn as normal mine carts on the other side...
MV-P: Issue where portal cool down's are not respected and an entity (ie: minecart) will "multiplex" or duplicate as it gets stuck in an infinite loop between 2 teleports (Causing severe server lag)

If I missed a Issue # please let me know.

**Comment by FernFerret** [comment]
Closing as not an issue (you've already mentioned other issues, but this is just a meta issue).
