### ISSUE TITLE
MV Portals.yml suggestion

### ISSUE THREAD

**Issue by pookshuman** [Multiverse/Multiverse-Portals#209]
Hello,

This is a suggestion for a future release. I noticed that if you have a lot of portals it can get confusing. It would be nice if there were a separate portals.yml for each world. This would be similar to the way Worldguard has separate world folders for its regions.

Anyhoo, just a thought.

**Comment by FernFerret** [comment]
Don't think we want to do this, at least not with yaml.

**Comment by pookshuman** [comment]
Thanks for responding so quickly :)

**Comment by FernFerret** [comment]
I know right? But in all seriousness, I'm cleaning the tracker so we can actually use it :)

I'm not one to turn down requests, but I don't see a use case for this. If we ever moved to something other than tank (i.e. SQLite) I could see putting them in different configs.

You'll have to appreciate how much work configuration migration is if you look at the trail of migration methods strewn about the code, and I don't have the time to support that without a very good reason.
