### ISSUE TITLE
Some portals not working, others do

### ISSUE THREAD

**Issue by SparcleeLasagnia** [Multiverse/Multiverse-Portals#241]
On my server I use Multiverse Portals for the majority of the teleporting. I just recently got a generator that makes a floating islands world (http://dev.bukkit.org/server-mods/floating-isles/). When i tried to set a portal to tp to the new world, it wouldnt work. I tried different names, different locations, and different destinations, but the portal will not work. I then had users complaining about another portal not working, one that teleports to a 8x scaled world (http://dev.bukkit.org/server-mods/maxiworld/).
I would greatly appreciate it if someoe were to help or suggest how to fix this issue. I am currently using essentials warps to teleport players to these worlds, but i would like there to be portals since they look better, and dont cause a delay for default players (I have 1 second delay before tp).
Thank you!

**Comment by Bubbleblyat** [comment]
I have the same problem! help would be much appreciated! portal_b TO portal_a works but not portal_a TO portal_b. Done everything that has been said on this post but still not working unfortunately.
