### ISSUE TITLE
Entering a multiverse dimension and loogging out prevents the user from logging in again

### ISSUE THREAD

**Issue by Braydo99** [Multiverse/Multiverse-Portals#268]
Entering a multiverse portal and into a new world generated by multiverse is alright until you log out in one of those worlds. Upon trying to log back on, you get this error-
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 7/2/13 11:22 AM
Description: Ticking screen

java.lang.IllegalArgumentException: Could not get provider type for dimension 22, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:150)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:299)
	at aaq.a(WorldProvider.java:208)
	at ayp.<init>(WorldClient.java:60)
	at ayh.a(NetClientHandler.java:307)
	at dw.a(Packet1Login.java:119)
	at cg.b(TcpConnection.java:458)
	at ayh.d(NetClientHandler.java:240)
	at ayk.c(GuiConnecting.java:49)
	at net.minecraft.client.Minecraft.l(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.J(Minecraft.java:848)
	at net.minecraft.client.Minecraft.run(Minecraft.java:773)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:150)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:299)
	at aaq.a(WorldProvider.java:208)
	at ayp.<init>(WorldClient.java:60)
	at ayh.a(NetClientHandler.java:307)
	at dw.a(Packet1Login.java:119)
	at cg.b(TcpConnection.java:458)
	at ayh.d(NetClientHandler.java:240)
	at ayk.c(GuiConnecting.java:49)

-- Affected screen --
Details:
	Screen name: ayk
Stacktrace:
	at net.minecraft.client.Minecraft.l(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.J(Minecraft.java:848)
	at net.minecraft.client.Minecraft.run(Minecraft.java:773)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.4.7
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 239749240 bytes (228 MB) / 484900864 bytes (462 MB) up to 1849229312 bytes (1763 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
	FML: MCP v7.26a FML v4.7.35.556 Minecraft Forge 6.6.2.534 Optifine OptiFine_1.4.6_HD_D5 55 mods loaded, 55 mods active
	mcp [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore [CodeChicken Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems [Not Enough Items] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PowerCrystalsCore [PowerCrystals Core] (coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_bspkrsCore [bspkrsCore] ([1.4.7]bspkrsCorev2.02.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Castle Defenders [Castle Defenders] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TreeCapitator [TreeCapitator] ([1.4.6]TreeCapitator.Forge.1.4.6.r07.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomLAN [Custom LAN Mod] (CustomPortForge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GuiAPI [GuiAPI] (GuiAPI-1.4.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SAP_Man [SanAndreasPs Managers] (0_SAPManPack_v13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ReiMinimap [mod_ReiMinimap] ([1.4.7]ReiMinimap_v3.2_06.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_AdvancedHud [mod_AdvancedHud] (Advanced Hud 4.8.1 [1.4.6].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2 [IndustrialCraft 2] (industrialcraft-2_1.115.231-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel [Advanced Solar Panels] (Advanced-Solar-Panels-Addon-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedMachines [IC2 Advanced Machines Addon] (AdvancedMachines_1.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AppliedEnergistics [Applied Energistics] (appeng-rv9-i.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core [BuildCraft] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders [BC Builders] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy [BC Energy] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory [BC Factory] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport [BC Transport] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon [BC Silicon] (buildcraft-A-3.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CameraCraft [CameraCraft] (CameraCraft2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CatapultMod [Catapult Mod] (Catapult_Mod-0.8.6.133-alpha-MC146.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChickenChunks [ChickenChunks] (ChickenChunks 1.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CompactSolars [Compact Solar Arrays] (compactsolars-universal-1.4.7-4.0.3.29.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ClaySoldiersMod [Clay Soldiers Mod] (CSM_v9_05.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CustomSpawner [DrZhark's CustomSpawner] (Custom-Mob-Spawner-Mod-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DimensionalDoors [Dimensional Doors] (DimensionalDoors-1.4.7 v1.3.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	kirsybuuDoubleDoorMod [Double Door Mod] (doubledoor-forge-v4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MoCreatures [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v4.5.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_maze [mod_maze] (DynamicMazes1.2[1.4.7].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FlatBedrock [FlatBedrock] (FlatBedrock_1.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry [Forestry for Minecraft] (forestry-A-1.7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest [Iron Chest] (ironchest-universal-1.4.7-5.1.0.275.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_MAtmos [mod_MAtmos] (matmos_packaged.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Millenaire [Millénaire] (millenaire4.3.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ModularForceFieldSystem [Modular ForceField System V2] (Modular-Force-Field-System-Addon.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mmmPowersuits [MachineMuse's Modular Powersuits] (ModularPowersuits-0.3.2-199.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	More Pistons [More Pistons] (More Pistons v1.2.4 for [1.4.7].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PowerConverters [Power Converters] (PowerConverters-2.2.2-29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerCore [RedPower] (RedPower-2-Core-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerBase [RP Base] (RedPower-2-Core-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerMachine [RP Machine] (RedPower-2-Mechanical-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerCompat [RP Compat] (RedPower-2-Compat-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerWiring [RP Wiring] (RedPower-2-Digital-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerLogic [RP Logic] (RedPower-2-Digital-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerLighting [RP Lighting] (RedPower-2-Digital-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerWorld [RP World] (RedPower-2-Mechanical-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RedPowerControl [RP Control] (RedPower-2-Mechanical-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TC [Traincraft] (Traincraft-3.1.13_030.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	snyke7_Transformers [Transformers] (Transformers-Addon.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WildCaves3 [Wild Caves 3] (Wild-Caves-Mod-1.4.7.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LWJGL: 2.4.2
	OpenGL: ATI Radeon HD 4600 Series  GL version 3.3.10362 Compatibility Profile Context, ATI Technologies Inc.
	Is Modded: Definitely; Client brand changed to 'forge,fml'
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

In order to get back on, I have to delete the players .dat file to let them back on! I use a modded server with MCPC+, and really need some help! The server I use is at http://www.technicpack.net/modpack/details/millenaire-elite.95098, if it helps!

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
