### ISSUE TITLE
Suggestion, MV-Portals: Severance of dependency on MV-Core

### ISSUE THREAD

**Issue by jflory7** [Multiverse/Multiverse-Portals#302]
Hello MV Team,

As a long time user of Multiverse, I greatly appreciate the work you've done on the Multiverse suite so far – it's very impressive!

One thing I've always wanted was to run Multiverse-Portals as a standalone plugin without being dependent on Multiverse-Core. As a minimalist, I always have preferred to keep things as low maintenance as possible on my server, and I only like to have installed what I am actively using.

As my main server doesn't require multiple worlds, when I use MV-Portals, I only would use the Core to get Portals working. However, I never use any of the functions of the Core. I just like to use portals with WorldEdit regions to help coordinate movement of my players across a single world.

What I'm suggesting is perhaps severing the required dependency of MV-Portals on MV-Core. I'm not sure how you all have the system set up now, but in my eyes, it seems like a good idea.

Interested to hear what you all have to think.

- jflory7

**Comment by TWSSYesterday** [comment]
Whilst it'd be nice, it distracts from the whole Multiverse principle. Sorry for the two year and a bit wait on this.

**Comment by FernFerret** [comment]
I mean, you don't have to use any of the core functions, but Multiverse-Portals is super-dependent on Core.
