### ISSUE TITLE
Issue using world edit wand to create portal

### ISSUE THREAD

**Issue by Airglow26** [Multiverse/Multiverse-Portals#316]
Airglow26 issued server command: /mvp create town p:portal
00:31:09 BST CONSOLE: [INFO] WEAPI
00:31:09 BST CONSOLE: ERROR]: null
00:31:09 BST CONSOLE: exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b710
00:31:09 BST CONSOLE: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;

**Comment by FernFerret** [comment]
Looks like this was fixed https://github.com/Multiverse/Multiverse-Portals/commit/a6694b955eff8f399da736c941423bb16a800287

Closing as duplicate and resolved.
