### ISSUE TITLE
Add effects to portals

### ISSUE THREAD

**Issue by Squawkers13** [Multiverse/Multiverse-Portals#337]
I was thinking, maybe you could add configurable visual/sound effects to portals?
(Ex: Walk in, sound plays, lightning strike, tp after delay?)

**Comment by FernFerret** [comment]
I'm not sure how feasible this is but it would be neat... There's a good chance you could also get this accomplished with command blocks.

**Comment by FernFerret** [comment]
Closing as duplicate of #322
