### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by minecraftboy4500** [Multiverse/Multiverse-Portals#354]
Every time i try to create a portal it says internal error

**Comment by Ironic8b498** [comment]
I have the same issue I was able to create a portal manually. Since I'm running Worldedit 6.0 and have to run it for other plugins, I just copied and pasted a portal in the portals.yml file and edited with correct cords and changed portal name and destination worked great.

**Comment by LightningJimmy** [comment]
@Ironic8b498  Can you give me the code for the portal to put in the "portals.yml" file? Thanks

**Comment by LightningJimmy** [comment]
Now, I don't need the code. I found a way to solve the problem!

I copied this over from my other post:
The best way is to get a different version of WorldEdit:
Replace the World Edit 6.0 with this:
http://adf.ly/wN3d5

Important: This download uses an adf.ly link shortener for the download. Just wait 5 seconds and click "Skip Ad" in the top-right corner to proceed to the download page.
