### ISSUE TITLE
Not compatible with WorldEdit 6.x Internal Error

### ISSUE THREAD

**Issue by ssamjh** [Multiverse/Multiverse-Portals#355]
Explains it all. If you need a lot, tell me.

**Comment by Ironic8b498** [comment]
I have the same issue I was able to create a portal manually. Since I'm running Worldedit 6.0 and have to run it for other plugins, I just copied and pasted a portal in the portals.yml file and edited with correct cords and changed portal name and destination worked great.

**Comment by Uncleleech** [comment]
Seems to be a real issue, several merge requests are out but the team appears to be inactive.

**Comment by dumptruckman** [comment]
I only see one pull request that attempts to fix this.  I have made comments on the problems it introduces and the developer responsible for it has yet to respond.

**Comment by Uncleleech** [comment]
https://github.com/dmulloy2/Multiverse-Portals/releases Seems to have a working version.

**Comment by dumptruckman** [comment]
It'd be lovely if they made a pull request....

**Comment by Uncleleech** [comment]
Yeah, I guess.

**Comment by dumptruckman** [comment]
No wait.. that is the one that is on the PR.  So, I'm just waiting for him to fix it.

**Comment by Uncleleech** [comment]
Okay, cool. It'd be nice to see support for WE 6.

**Comment by LightningJimmy** [comment]
I copied this over from my other post:
The best way is to get a different version of WorldEdit:
Replace the World Edit 6.0 with this:
http://adf.ly/wN3d5

Important: This download uses an adf.ly link shortener for the download. Just wait 5 seconds and click "Skip Ad" in the top-right corner to proceed to the download page.

**Comment by Uncleleech** [comment]
Jimmy, this is a workaround, however we5 won't work with some plugins. We
need MVP to work with we6.

**Comment by FuRiouSOne** [comment]
https://github.com/dmulloy2/Multiverse-Portals/releases Version works perfect with WE6 thanks!

**Comment by Uncleleech** [comment]
Yeah, that's cool but as @dumptruckman said it's not being pulled yet and the author doesnt seem to want to make the changes.

dmulloy2's one works okay but i'd rather an official on this repo.
