### ISSUE TITLE
"An internal error ocurred" when creating portal

### ISSUE THREAD

**Issue by Tatoncho** [Multiverse/Multiverse-Portals#360]
Hi, I'm having problems creating portals... I get the wand (wooden Axe), set the 3x3 area to place the portal, but when I type the command /mvp create example example the server says "an internal error ocurred......" and nothing happens...

Here is my list of plugins installed:

[13:28:41 INFO]: Plugins (23): CoreProtect, BOSEconomy, WorldEdit, Essentials, E
ssentialsProtect, EssentialsChat, GroupManager, SafeExplosions, EssentialsAntiBu
ild, Buycraft, Announcer, SetLobby, xAuth, Lockette, Vault, EssentialsSpawn, Mul
tiverse-Core, WorldGuard, dynmap, ChestShop, Jobs, Multiverse-Portals, iZone

and here is the link to my last log where you can see the issue: http://www.heypasteit.com/clip/1RAP

**Comment by LightningJimmy** [comment]
You have to uninstall WorldEdit. I had this problem too and when I uninstalled WorldEdit, everything ran perfectly.

**Comment by Tatoncho** [comment]
But I need WorldEdit too... there must be a way to make both plugins run together...

**Comment by Tatoncho** [comment]
Considering what "LightningJimmy" said, I check the wand config and try to set item ID 290 (wooden Hoe) as multiverse-portals wand... but it work as a normal item destroying the blocks I click on...

**Comment by LightningJimmy** [comment]
The best way is to get a different version of WorldEdit:
Replace the World Edit 6.0 with this:
http://adf.ly/wN3d5

Important: This download uses an adf.ly link shortener for the download. Just wait 5 seconds and click "Skip Ad" in the top-right corner to proceed to the download page.

**Comment by FuRiouSOne** [comment]
https://github.com/Multiverse/Multiverse-Portals/issues/364

**Comment by FuRiouSOne** [comment]
https://github.com/dmulloy2/Multiverse-Portals/releases Version works perfect with WE6

**Comment by Tatoncho** [comment]
It works perfectly now with that version!!!! Thank you very much to all of you!!!
