### ISSUE TITLE
Multiverse portals not working.

### ISSUE THREAD

**Issue by SJ321987** [Multiverse/Multiverse-Portals#364]
When I try to create a portal I get 'An internal error occurred while attempting to preform this command."

Console: 
24.01 22:53:06 [Server] INFO ... 14 more
24.01 22:53:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
24.01 22:53:06 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
24.01 22:53:06 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
24.01 22:53:06 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
24.01 22:53:06 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
24.01 22:53:06 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
24.01 22:53:06 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
24.01 22:53:06 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
24.01 22:53:06 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
24.01 22:53:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fa7cbf9-59dd2dd]
24.01 22:53:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
24.01 22:53:06 [Server] ERROR null
24.01 22:53:06 [Server] INFO WEAPI

**Comment by Dandiestdog** [comment]
I have the same issue.

**Comment by tigerboy1004** [comment]
I have it too D: please someone  help us

**Comment by tigerboy1004** [comment]
i have it too D: someone please help us

**Comment by FuRiouSOne** [comment]
Same issue here, apparently World Edit 6 made some changes to their API and MV is not reading it properly anymore...

**Comment by FuRiouSOne** [comment]
Spoke to @sk89q and he says Multiverse team needs to update to use the new API within World Edit 6  for this to work.

**Comment by FuRiouSOne** [comment]
https://github.com/dmulloy2/Multiverse-Portals/releases Version works perfect with WE6
