### ISSUE TITLE
Can't create portal

### ISSUE THREAD

**Issue by darkwolf706** [Multiverse/Multiverse-Portals#366]
Here's what happens when I do in my console /mvpc PVP:

06.02 15:51:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lWant to be Batman, or IronMan? Or have them fight eachother?!?!!?! /warp marvelvsdc!
06.02 15:51:26 [Server] INFO SaraBellaToo fell from a high place
06.02 15:51:25 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: weeeeee
06.02 15:51:06 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: Oh ok tmi
06.02 15:50:57 [Server] INFO [**Donuts][Member]  pizza320 : (i gotta poo)
06.02 15:50:49 [Server] INFO ------------------------------------------ 
06.02 15:50:49 [Server] INFO Saved 0 marriages.
06.02 15:50:49 [Server] INFO -------- AutoSaving Marriage Data -------- 
06.02 15:50:44 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: that sounds...wierd
06.02 15:50:31 [Server] INFO [**Donuts][Member]  pizza320 : brb
06.02 15:50:30 [Server] INFO ... 14 more
06.02 15:50:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
06.02 15:50:30 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
06.02 15:50:30 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
06.02 15:50:30 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
06.02 15:50:30 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
06.02 15:50:30 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
06.02 15:50:30 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
06.02 15:50:30 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
06.02 15:50:30 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
06.02 15:50:30 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-BT27.jar:git-Bukkit-bc03b6f]
06.02 15:50:30 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvpc' in plugin Multiverse-Portals v2.5-b699
06.02 15:50:30 [Server] ERROR null
06.02 15:50:30 [Server] INFO WEAPI
06.02 15:50:28 [Server] INFO [**Donuts][Member]  pizza320 : i gotta play some angry turds
06.02 15:50:12 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: wana try?
06.02 15:50:07 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: this is a new pvp map
06.02 15:49:48 [Server] INFO Giving 64 of arrow to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of bow to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of leather chestplate to  pizza320.
06.02 15:49:48 [Server] INFO Error: Unknown item name: leatherchest.
06.02 15:49:48 [Server] INFO Giving 1 of leather boots to  pizza320.
06.02 15:49:48 [Server] INFO Error: Unknown item name: leatherchest.
06.02 15:49:48 [Server] INFO Giving 16 of torch to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of stone spade to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of stone axe to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of stone pickaxe to  pizza320.
06.02 15:49:48 [Server] INFO Giving 1 of stone sword to  pizza320.
06.02 15:49:39 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: OH OH do /zone terminal
06.02 15:49:30 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: this is a new game called pirates
06.02 15:49:18 [Server] INFO [**Donuts][Member]  pizza320 : im on some island
06.02 15:49:14 [Server] INFO [**Donuts][Member]  pizza320 : i think
06.02 15:49:09 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: oh =(
06.02 15:49:06 [Server] INFO [**Donuts][Member]  pizza320 : ]
06.02 15:49:03 [Server] INFO [**Donuts][Member]  pizza320 : spawn
06.02 15:48:56 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: whered u go?
06.02 15:48:10 [Server] INFO [**Donuts][Member]  pizza320 : no shame
06.02 15:48:00 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: lol
06.02 15:46:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lCheck out our new Town RP World! /warp townworld!
06.02 15:46:16 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: GO
06.02 15:46:10 [Server] INFO [**Donuts][Member]  pizza320 : yes
06.02 15:46:04 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: ok ready?
06.02 15:45:58 [Server] INFO [**Donuts][Member]  pizza320 : yeah
06.02 15:45:53 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: is it working now?
06.02 15:45:23 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: ok im ready
06.02 15:45:03 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: good
06.02 15:45:00 [Server] INFO [**Donuts][Member]  pizza320 : i killed it
06.02 15:44:37 [Server] INFO [**Donuts][Member]  pizza320 : ill kill it
06.02 15:44:28 [Server] WARN [SurvivalGames] could not check for updates.
06.02 15:44:28 [Server] INFO [SG]Checking for updates
06.02 15:44:26 [Server] INFO [**Donuts][Member]  pizza320 : vreeper at spawn
06.02 15:44:25 [Multicraft] DarkWolf706 ran command Message of the Day
06.02 15:44:25 [Connect] User DarkWolf706, IP 24.236.99.100
06.02 15:44:25 [Server] INFO UUID of player DarkWolf706 is 571a99a2-56af-466e-96be-497b3fb885c2
06.02 15:44:19 [Server] INFO DarkWolf706 left the game.
06.02 15:44:19 [Disconnect] User DarkWolf706 has disconnected, reason: Disconnected
06.02 15:44:19 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: brb
06.02 15:43:57 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: hang on waorking on it
06.02 15:43:42 [Server] INFO [**Donuts][Member]  pizza320 : nvm
06.02 15:43:39 [Server] INFO [**Donuts][Member]  pizza320 : help im burning
06.02 15:43:38 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: No I did what I wanted
06.02 15:43:36 [Server] INFO Saved the world
06.02 15:43:36 [Server] INFO Saving...
06.02 15:43:36 [Server] INFO Saving is already turned on.
06.02 15:43:36 [Multicraft] Auto-saving world...
06.02 15:43:22 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: lol u tried
06.02 15:43:19 [Server] INFO pizza320 fell out of the world
06.02 15:43:17 [Server] INFO [**Donuts][Member]  pizza320 : aaah
06.02 15:43:15 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: h
06.02 15:42:59 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: hang on let me relocate this
06.02 15:42:53 [Server] INFO [**Donuts][Member]  pizza320 : SORRY, BUT YOU CANT OPEN THAT HERE
06.02 15:42:51 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: ...again...wierd
06.02 15:42:40 [Server] INFO [**Donuts][Member]  pizza320 : smoke puffs up and it says
06.02 15:42:29 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: hang on
06.02 15:42:25 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: wierd
06.02 15:42:21 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: thats woerd
06.02 15:42:15 [Server] INFO [**Donuts][Member]  pizza320 : like i cant open the chest
06.02 15:42:12 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: I'm not sure
06.02 15:41:56 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: i know me too
06.02 15:41:46 [Server] INFO [**Donuts][Member]  pizza320 : also i cant do anything
06.02 15:41:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lCheck out our website! http://darkwolfgames.net
06.02 15:41:31 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: how do you make an island able to pvp
06.02 15:41:23 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: ?
06.02 15:41:19 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: chris
06.02 15:41:13 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: tiny problem
06.02 15:41:06 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: wait
06.02 15:41:03 [Server] INFO [**Donuts][Member]  pizza320 : i cant open the chest
06.02 15:41:00 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: GO
06.02 15:40:57 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: LOL NOPE
06.02 15:40:46 [Server] INFO [**Donuts][Member]  pizza320 : like the sadness you will feel when you perish
06.02 15:40:45 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: rdy?
06.02 15:40:32 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: lol
06.02 15:40:28 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: ok
06.02 15:40:24 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: XD NO MINE IS BLUE
06.02 15:40:15 [Server] INFO [**Donuts][Member]  pizza320 : RED THE COLOR OF THE BLOOD OF MY ENEMYS
06.02 15:40:02 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: red or blue?
06.02 15:39:49 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: XD WE WILL SEEE
06.02 15:39:42 [Server] INFO [**Donuts][Member]  pizza320 : YOU WILL PERISH
06.02 15:39:40 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: tp :)
06.02 15:39:36 [Server] INFO [**Donuts][Member]  pizza320 : ME
06.02 15:39:28 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: who wants to have a snowball fight with me? =D
06.02 15:37:47 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: hai =)
06.02 15:37:42 [Server] INFO [**Donuts][Member]  pizza320 : hi
06.02 15:37:36 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: wb
06.02 15:37:35 [Server] INFO [DarkWolf706: Toggled downfall]
06.02 15:37:29 [Multicraft] pizza320 ran command Message of the Day
06.02 15:37:29 [Connect] User pizza320, IP 72.89.138.137
06.02 15:37:29 [Server] INFO UUID of player pizza320 is 9e48b8b2-91b8-4f6a-a471-eabe02091b5e
06.02 15:36:59 [Server] INFO pizza320 left the game.
06.02 15:36:58 [Disconnect] User pizza320 has disconnected, reason: Disconnected
06.02 15:36:58 [Server] INFO [**Donuts][Member]  pizza320 : brb
06.02 15:36:47 [Server] INFO [**Donuts][Member]  pizza320 : dongus
06.02 15:36:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] Check out our new minigame! /warp pirates!
06.02 15:36:36 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: nj doesn't come on either
06.02 15:36:28 [Server] INFO [**Donuts][Member]  pizza320 : dingus
06.02 15:36:15 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: not me
06.02 15:36:03 [Server] INFO [**Donuts][Member]  pizza320 : Has anyone seen nj i havnt seen him since last year
06.02 15:34:53 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: i know =(
06.02 15:34:50 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Kinda.. it was never official but...
06.02 15:34:36 [Server] INFO [**Donuts][Member]  pizza320 : WAAAAAAAT
06.02 15:34:33 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: all of them D:
06.02 15:34:25 [Server] INFO [**Donuts][Member]  pizza320 : wait they LEFT
06.02 15:34:16 [Server] INFO [**Donuts][Member]  pizza320 : *end
06.02 15:34:13 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: mata and ellie
06.02 15:34:09 [Server] INFO [**Donuts][Member]  pizza320 : but there is no t in the and
06.02 15:33:59 [Server] INFO [**Donuts][Member]  pizza320 : also the website says the serer ip is darkwolfgames mcserver wst
06.02 15:33:45 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: :(
06.02 15:33:41 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: gatechurch did
06.02 15:33:33 [Server] INFO Saved the world
06.02 15:33:33 [Server] INFO Saving...
06.02 15:33:33 [Server] INFO Saving is already turned on.
06.02 15:33:33 [Multicraft] Auto-saving world...
06.02 15:33:26 [Server] INFO [**Donuts][Member]  pizza320 : so did anyone else quit
06.02 15:32:10 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: XD
06.02 15:32:07 [Server] INFO [**Donuts][Member]  pizza320 : *vote
06.02 15:32:02 [Server] INFO [**Donuts][Member]  pizza320 : *ote
06.02 15:31:59 [Server] INFO [**Donuts][Member]  pizza320 : we dont have the right to ote
06.02 15:31:50 [Server] INFO [**Donuts][Member]  pizza320 : but me and kookie are like ham and cheese
06.02 15:31:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lWant to be Batman, or IronMan? Or have them fight eachother?!?!!?! /warp marvelvsdc!
06.02 15:31:28 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: kookie rage quit lol
06.02 15:31:12 [Server] INFO [**Donuts][Member]  pizza320 : D:
06.02 15:31:04 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: He quit
06.02 15:31:00 [Server] INFO [**Donuts][Member]  pizza320 : the shop kookie was making\
06.02 15:30:33 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: I dont remember what shop...
06.02 15:30:24 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: I cant remember...
06.02 15:30:08 [Server] INFO [**Donuts][Member]  pizza320 : DID YOU GUYS FINISH THE SHOP
06.02 15:30:05 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: better?
06.02 15:29:54 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: how are you :)
06.02 15:29:52 [Server] INFO [**Donuts][Member]  pizza320 : im starving to death
06.02 15:29:35 [Server] INFO [+DarkEmpire][Admin]  SoLaRfLaRe: hai!
06.02 15:29:32 [Server] INFO [**Donuts][Member]  pizza320 : HI
06.02 15:29:30 [Server] WARN [SurvivalGames] could not check for updates.
06.02 15:29:29 [Server] INFO [SG]Checking for updates
06.02 15:29:27 [Multicraft] SaraBellaToo ran command Message of the Day
06.02 15:29:27 [Connect] User SaraBellaToo, IP 69.254.4.198
06.02 15:29:26 [Server] INFO UUID of player SaraBellaToo is f8e924cd-290f-4a02-9a0b-a3a9b045820b
06.02 15:28:58 [Server] INFO [**Donuts][Member]  pizza320 : does more damage
06.02 15:28:54 [Server] INFO [**Donuts][Member]  pizza320 : and weapon designs like instead of wood you could use bone to make a bone handle easier to break but
06.02 15:28:09 [Server] INFO GroupManager - INFO -  Data files refreshed.
06.02 15:27:40 [Server] INFO [**Donuts][Member]  pizza320 : ikr'
06.02 15:27:36 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: That'd be cool!
06.02 15:27:08 [Server] INFO [**Donuts][Member]  pizza320 : they should have an update where you can change your bed blanket with dye I:
06.02 15:26:39 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lCheck out our new Town RP World! /warp townworld!
06.02 15:25:46 [Server] INFO pizza320 has just earned the achievement [Taking Inventory]
06.02 15:25:33 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Oh god
06.02 15:25:25 [Server] INFO [**Donuts][Member]  pizza320 : it has begun
06.02 15:25:16 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Of course! lol
06.02 15:24:55 [Server] INFO pizza320 created a new faction: Donuts
06.02 15:24:55 [Server] INFO setFactionId moved 9e48b8b2-91b8-4f6a-a471-eabe02091b5e aka  pizza320 from none aka Wilderness to d161318f-fb4d-48fc-9280-9fd5f73c652c aka Donuts.
06.02 15:24:27 [Server] INFO [Wilderness][Member]  pizza320 : i like the old one im attached to it
06.02 15:24:23 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: More interesting
06.02 15:24:20 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Much much better
06.02 15:24:13 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: do /warp pirates
06.02 15:24:10 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Haha, we actually have a new and improved factions game
06.02 15:23:32 [Server] INFO [Wilderness][Member]  pizza320 : all my "hard work"
06.02 15:23:30 [Server] INFO Saved the world
06.02 15:23:30 [Server] INFO Saving...
06.02 15:23:30 [Server] INFO Saving is already turned on.
06.02 15:23:30 [Multicraft] Auto-saving world...
06.02 15:23:01 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: so dont get too attached lol
06.02 15:23:01 [Server] INFO [Wilderness][Member]  pizza320 : NOOOOOOOOOOOOOOOOOOOO
06.02 15:22:55 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: We're gonna reset it soon
06.02 15:22:44 [Server] INFO [Wilderness][Member]  pizza320 : im in now
06.02 15:22:25 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: walk all the way through
06.02 15:22:20 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: I can
06.02 15:22:07 [Server] INFO [Wilderness][Member]  pizza320 : lol
06.02 15:22:03 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: I'm not that good, i really just photo edited lol
06.02 15:22:02 [Server] INFO [Wilderness][Member]  pizza320 : why cant i go into factions portal
06.02 15:21:40 [Server] INFO §2§l[§5§lDarkWolfGames§r§2§l] §4§lCheck out our website! http://darkwolfgames.net
06.02 15:21:40 [Server] INFO Files auto-saved.
06.02 15:21:21 [Server] INFO [Wilderness][Member]  pizza320 : cool best i can make is a green guy with blue eyes
06.02 15:21:14 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: I like your skin
06.02 15:21:01 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Well, took elements from other people, but combined it myself
06.02 15:20:49 [Server] INFO ------------------------------------------ 
06.02 15:20:49 [Server] INFO Saved 0 marriages.
06.02 15:20:49 [Server] INFO -------- AutoSaving Marriage Data -------- 
06.02 15:20:49 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Made it myself
06.02 15:20:30 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Thanks man
06.02 15:20:24 [Server] INFO [Wilderness][Member]  pizza320 : nice new skin
06.02 15:20:13 [Server] INFO You changed player 'pizza320' group to 'Default' in world 'world'.
06.02 15:20:13 [Server] INFO Couldn't retrieve your world. Default world 'world' selected.
06.02 15:19:22 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: We have a tutorial
06.02 15:19:14 [Server] INFO [**DarkEmpire][i]Owner[i] DarkWolf706: Hey
06.02 15:18:40 [Server] INFO §cpizza320 §4was denied access to command.
06.02 15:18:35 [Server] INFO §cpizza320 §4was denied access to command.
06.02 15:18:13 [Multicraft] pizza320 ran command Message of the Day
06.02 15:18:13 [Connect] User pizza320, IP 72.89.138.137
06.02 15:18:13 [Server] INFO UUID of player pizza320 is 9e48b8b2-91b8-4f6a-a471-eabe02091b5e
06.02 15:18:09 [Server] INFO GroupManager - INFO -  Data files refreshed.
06.02 15:18:08 [Server] WARN [SurvivalGames] could not check for updates.
06.02 15:18:08 [Server] INFO [SG]Checking for updates
06.02 15:18:05 [Multicraft] DarkWolf706 ran command Message of the Day
06.02 15:18:05 [Connect] User DarkWolf706, IP 24.236.99.100
06.02 15:18:04 [Server] INFO UUID of player DarkWolf706 is 571a99a2-56af-466e-96be-497b3fb885c2
06.02 15:16:34 [Server] INFO pizza320 left the game.
06.02 15:16:34 [Disconnect] User pizza320 has disconnected, reason: Disconnected
06.02 15:15:20 [Server] WARN §4That kit does not exist.
06.02 15:15:19 [Multicraft] pizza320 ran command Message of the Day
06.02 15:15:19 [Connect] User pizza320, IP 72.89.138.137
06.02 15:15:19 [Server] INFO UUID of player pizza320 is 9e48b8b2-91b8-4f6a-a471-eabe02091b5e
06.02 15:13:27 [Server] INFO Saved the world
06.02 15:13:27 [Server] INFO Saving...
06.02 15:13:27 [Server] INFO Saving is already turned on.
06.02 15:13:27 [Multicraft] Auto-saving world...
06.02 15:03:24 [Server] INFO Saved the world
06.02 15:03:24 [Server] INFO Saving...
06.02 15:03:24 [Server] INFO Saving is already turned on.
06.02 15:03:24 [Multicraft] Auto-saving world...
06.02 14:53:21 [Server] INFO Saved the world
06.02 14:53:21 [Server] INFO Saving...
06.02 14:53:21 [Server] INFO Saving is already turned on.
06.02 14:53:21 [Multicraft] Auto-saving world...
06.02 14:50:49 [Server] INFO ------------------------------------------ 
06.02 14:50:49 [Server] INFO Saved 0 marriages.
06.02 14:50:49 [Server] INFO -------- AutoSaving Marriage Data -------- 
06.02 14:43:19 [Server] INFO Saved the world
06.02 14:43:19 [Server] INFO Saving...
06.02 14:43:19 [Server] INFO Saving is already turned on.
06.02 14:43:19 [Multicraft] Auto-saving world...
06.02 14:33:16 [Server] INFO Saved the world
06.02 14:33:16 [Server] INFO Saving...
06.02 14:33:16 [Server] INFO Saving is already turned on.
06.02 14:33:16 [Multicraft] Auto-saving world...
06.02 14:30:17 [Server] INFO Daniel_Hackett left the game.
06.02 14:30:17 [Disconnect] User Daniel_Hackett has disconnected, reason: Internal Exception: java.io.IOException: Connection reset by peer
06.02 14:28:02 [Server] INFO [Daniel_Hackett: Toggled downfall]
06.02 14:27:31 [Server] WARN [SurvivalGames] could not check for updates.
06.02 14:27:31 [Server] INFO [SG]Checking for updates
06.02 14:27:28 [Multicraft] Daniel_Hackett ran command Message of the Day
06.02 14:27:28 [Connect] User Daniel_Hackett, IP 73.190.247.2
06.02 14:27:28 [Server] INFO UUID of player Daniel_Hackett is 39c3ba3b-507d-4924-a092-2f7f05cc4c83
06.02 14:23:13 [Server] INFO Saved the world
06.02 14:23:13 [Server] INFO Saving...
06.02 14:23:13 [Server] INFO Saving is already turned on.
06.02 14:23:13 [Multicraft] Auto-saving world...
06.02 14:21:40 [Server] INFO Files auto-saved.
06.02 14:20:49 [Server] INFO ------------------------------------------ 
06.02 14:20:49 [Server] INFO Saved 0 marriages.
06.02 14:20:49 [Server] INFO -------- AutoSaving Marriage Data -------- 
06.02 14:13:10 [Server] INFO Saved the world
06.02 14:13:10 [Server] INFO Saving...
06.02 14:13:10 [Server] INFO Saving is already turned on.
06.02 14:13:10 [Multicraft] Auto-saving world...
06.02 14:03:07 [Server] INFO Saved the world
06.02 14:03:07 [Server] INFO Saving...
06.02 14:03:07 [Server] INFO Saving is already turned on.
06.02 14:03:07 [Multicraft] Auto-saving world...
06.02 13:53:04 [Server] INFO Saved the world
06.02 13:53:04 [Server] INFO Saving...
06.02 13:53:04 [Server] INFO Saving is already turned on.
06.02 13:53:04 [Multicraft] Auto-saving world...
06.02 13:50:49 [Server] INFO ------------------------------------------ 
06.02 13:50:49 [Server] INFO Saved 0 marriages.
06.02 13:50:49 [Server] INFO -------- AutoSaving Marriage Data -------- 
06.02 13:43:02 [Server] INFO Saved the world
06.02 13:43:02 [Server] INFO Saving...

**Comment by LavaGaming** [comment]
Same problem here :/

**Comment by LavaGaming** [comment]
Try using this: 
https://github.com/dmulloy2/Multiverse-Portals/releases
It's Multiverse Portals with the new WorldEdit API attached onto it. :)

**Comment by darkwolf706** [comment]
Thanks!
