### ISSUE TITLE
Portal Creation Failiure

### ISSUE THREAD

**Issue by LavaGaming** [Multiverse/Multiverse-Portals#367]
So I've updated to the latest WorldEdit, ever since I've not been able to create a portal. This is the error code I have retrieved.

07.02 15:50:42 [Server] INFO ... 14 more
07.02 15:50:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot%2018.jar:git-Spigot-13716d9-0899683]
07.02 15:50:42 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
07.02 15:50:42 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
07.02 15:50:42 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
07.02 15:50:42 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
07.02 15:50:42 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
07.02 15:50:42 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
07.02 15:50:42 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
07.02 15:50:42 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
07.02 15:50:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

Yes, it is backwards. Blame Multicraft.

**Comment by LavaGaming** [comment]
I'm going to use the fixed version for now:
https://github.com/dmulloy2/Multiverse-Portals/releases

**Comment by WanderingKazuma** [comment]
I am seeing the exact same thing.

**Comment by LavaGaming** [comment]
I actually closed this because I have an answer - someone has created a version supporting W/E v6: https://github.com/dmulloy2/Multiverse-Portals/releases
