### ISSUE TITLE
Teleport to random portal?

### ISSUE THREAD

**Issue by derpasaurs** [Multiverse/Multiverse-Portals#369]
Hello! Is the a way to teleport users randomly to different portals? (like /mvp modify dest p:portal1,portal2,portal3), If this is not a feature yet, when can you add it(or will you ;))

**Comment by dumptruckman** [comment]
This was added in b699 "rp:portal1:portal2:portal3"

**Comment by VirgilFabre** [comment]
I re open the thread years later, I need random location TO random location

I saw in config 
**location:** 32.0,98.0,-25.0**:**33.0,102.0,-24.0

So I expected I could set huge radius and let it work itself but now it only send me to the /mv spawn point using
location: -3000.0,50.0,-3000.0:3000.0,100.0,3000.0
