### ISSUE TITLE
dest not working

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Multiverse/Multiverse-Portals#371]
https://www.youtube.com/watch?v=LEsJwfSnP9A&feature=youtu.be

**Comment by FernFerret** [comment]
I'm sure dest is working fine, but you're not using it as an argument. The following should work for your portals:

```
/mvp select 1
/mvp modify dest p:2
/mvp select 2
/mvp modify dest p:1
```

**Comment by REVIEWGAMINGMAN** [comment]
did not work for me

**Comment by FernFerret** [comment]
I've never used numbers as portal names, perhaps that is it, but the video clearly showed you not using the command/arguments properly.

**Comment by REVIEWGAMINGMAN** [comment]
ok i wall try to do a test whit no numbers
