### ISSUE TITLE
Ingame And Console Command Error

### ISSUE THREAD

**Issue by XxAsSaSiNxX** [Multiverse/Multiverse-Portals#373]
Hi, In My Server I Have A Problem with Multiverse-Portals 2.4 Because:

1rst: I Select the Region With World edit Axe.
2nd: I Put The Comand /mvp create example
3rd Says An Internal Error Ocurred while attempting to perform this command.

Here The Console Error: http://pastebin.com/RM7TasWt

**Comment by xtoolbearx** [comment]
same here can somone help

**Comment by AnonymousMW3** [comment]
Same error...please fix it!

**Comment by AnonymousMW3** [comment]
(I am using Multiverse-Portals 2.5)
