### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mylesk23** [Multiverse/Multiverse-Portals#375]
I get a error An internal error occurred while attempting to perform this command.
I said Yoooo in chat then wrote the command:

06.04 20:52:48 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:48 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:48 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:46 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:46 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:46 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:46 [Multicraft] Skipped 3 lines due to rate limit (30/s)
06.04 20:52:44 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:44 [Server] INFO ... 14 more
06.04 20:52:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
06.04 20:52:44 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
06.04 20:52:44 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
06.04 20:52:44 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
06.04 20:52:44 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
06.04 20:52:44 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
06.04 20:52:44 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
06.04 20:52:44 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
06.04 20:52:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
06.04 20:52:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.1-20150304a.jar:git-Spigot-c3c767f-33d5de3]
06.04 20:52:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b699
06.04 20:52:44 [Server] ERROR null
06.04 20:52:44 [Server] INFO WEAPI
06.04 20:52:42 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:42 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:42 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:40 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:40 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:40 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:38 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:38 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:38 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:36 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:36 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:36 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:34 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:34 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:34 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.
06.04 20:52:32 [Server] INFO This may mean that any block logger / intercepters addons/plugins/mods that you have installed will not intercept WorldEdit's changes! Please notify the maintainer of the other addon about this.
06.04 20:52:32 [Server] ERROR Got request to set EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit but EditSessionFactories have been removed in favor of extending EditSession's extents.
06.04 20:52:32 [Server] INFO World edit session not set to AsyncWorldedit. Fixing.

**Comment by TWSSYesterday** [comment]
Using incompatible version of WorldEdit, revert to the 5.x branch or use @dmulloy's fork
