### ISSUE TITLE
Some Portals stopped working

### ISSUE THREAD

**Issue by K475u** [Multiverse/Multiverse-Portals#376]
Ok i have set up 6 Portals all with anchors as Destination ! All worked fine, after a Server Restart or a /mv reload, 2 of the 6 Portals  Stopped working the Destination in the config is invalid, but they worked before

  SpShangri:
    entryfee:
      currency: -1
      amount: 0.0
    safeteleport: true
    teleportnonplayers: false
    handlerscript: ''
    owner: Nobokatsu
    location: -752.0,72.0,2334.0:-749.0,75.0,2334.0
    world: Hades
    destination: i:Invalid Destination

**Comment by MinesanityPvP** [comment]
Please use the latest Multiverse-Core version listed in the development builds. These can be found on the Jenkins site! If this doesnt work, please report back!

**Comment by dumptruckman** [comment]
You need to update to the latest developmental builds of Core and Portals available here: http://ci.onarandombox.com/view/Multiverse/
