### ISSUE TITLE
Client dismounts when crossing portal in vehicle

### ISSUE THREAD

**Issue by mvaughn-echo** [Multiverse/Multiverse-Portals#377]
In spigot-1.8.3...

When crossing a standard Multiverse Portal to another world while in a vehicle (either a minecart or a boat), both the player and the vehicle will be transported to the target world as expected, but with one strange effect:

The client effectively no longer considers the player 'mounted' on the vehicle, but the server does. This results in an experience where **the vehicle appears to race away from the player** for one second, **then the player's position 'catches up'** to the vehicle's position. This continues (the player catching up to the vehicle's inertial motion every one second) until the player is forced to decouple from the vehicle, either by the vehicle's destruction or by inputting LSHIFT (dismount).

Nothing unusual is logged, even on the highest debug modes.

**Comment by MinesanityPvP** [comment]
This is not a bug. I believe this is an issue related with Minecraft itself.
