### ISSUE TITLE
Internal error occured while attempting to perform this command.

### ISSUE THREAD

**Issue by tristanphan** [Multiverse/Multiverse-Portals#378]
While I was trying to make a new portal, i received this error:
Internal error occured while attempting to perform this command.

I typed in this comand: /mvp create KitPVP

**Comment by LordDWT** [comment]
Same Problem for me.
http://pastebin.com/aRNzr9n5

Multiverse-Portals version 2.5-b713
This server is running CraftBukkit version git-Spigot-ae40327-8c14eb4 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)

**Comment by Ghost-Sailor** [comment]
Caused by conflict with WorldEdit, as has been noticed by several other users. Disabling WorldEdit while making the portal, and then enabling again after is a temporary workaround.
