### ISSUE TITLE
Teleportation and Portals????

### ISSUE THREAD

**Issue by fidelianerina** [Multiverse/Multiverse-Portals#379]
So im making a hub to do factions, mini games, skyblock and creative. But when i try to TP to a world, it wont work. And it wont let me make the portals either. Ive done the commands it gives and it gives me an error message. How can i fix this? Ive spent several hours trying to look this up but ive found nothing that helps.
Message for teleportation: Multiverse does not know how to take you to {name of world}
Message for making a portal: An internal error occurred while attempting to perform this command

So for example i try to go to Factions so i do:
/mvtp {my user} Factions
/mv tp {my user} Factions

/mvp create ToFactions Factions (since the command it /mvp create {Name} {Destination} )

**Comment by Asuza** [comment]
Do you have WorldEdit installed? If so, try removing it before creating a portal.

**Comment by MinesanityPvP** [comment]
Please use the latest Multiverse-Core version listed in the development builds. These can be found on the Jenkins site!

**Comment by dumptruckman** [comment]
You need to update to the latest developmental builds of Core and Portals available here: http://ci.onarandombox.com/view/Multiverse/
