### ISSUE TITLE
Inventories are not different

### ISSUE THREAD

**Issue by yoshee08** [Multiverse/Multiverse-Portals#381]
25.06 10:32:17 [Server] INFO No update was found.
25.06 10:32:13 [Server] INFO ... 32 more
25.06 10:32:13 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
25.06 10:32:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:189) ~[?:?]
25.06 10:32:13 [Server] INFO at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:60) ~[?:?]
25.06 10:32:13 [Server] INFO at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:86) ~[?:?]
25.06 10:32:13 [Server] INFO at com.onarandombox.multiverseinventories.ShareHandler.updateProfile(ShareHandler.java:114) ~[?:?]
25.06 10:32:13 [Server] INFO at com.onarandombox.multiverseinventories.api.share.Sharables$18.updateProfile(Sharables.java:533) ~[?:?]
25.06 10:32:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
25.06 10:32:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
25.06 10:32:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins-1.2.8.jar:?]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) [PerWorldPlugins-1.2.8.jar:?]
25.06 10:32:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
25.06 10:32:13 [Server] INFO at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.creativegates.MainListener.useGate(MainListener.java:268) [CreativeGates.jar:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.creativegates.entity.UGate.transport(UGate.java:188) [CreativeGates.jar:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.massivecore.mixin.Mixin.teleport(Mixin.java:226) [MassiveCore(4).jar:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.massivecore.mixin.TeleportMixinAbstract.teleport(TeleportMixinAbstract.java:61) [MassiveCore(4).jar:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.massivecore.mixin.TeleportMixinDefault.teleport(TeleportMixinDefault.java:116) [MassiveCore(4).jar:?]
25.06 10:32:13 [Server] INFO at com.massivecraft.massivecore.mixin.TeleportMixinDefault.teleportPlayer(TeleportMixinDefault.java:53) [MassiveCore(4).jar:?]
25.06 10:32:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.teleport(CraftEntity.java:223) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.teleport(CraftPlayer.java:475) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:580) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins-1.2.8.jar:?]
25.06 10:32:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot25.jar:git-Spigot-b1e6da1-1092acb]
25.06 10:32:13 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
25.06 10:32:13 [Server] INFO org.bukkit.event.EventException
25.06 10:32:13 [Server] INFO Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories

**Comment by MinesanityPvP** [comment]
Please use the latest Multiverse-Core version listed in the development builds. These can be found on the Jenkins site!

**Comment by dumptruckman** [comment]
You need to update to the latest developmental build of Core available here: http://ci.onarandombox.com/view/Multiverse/
