### ISSUE TITLE
Cant create portals

### ISSUE THREAD

**Issue by PureCrispyBacon** [Multiverse/Multiverse-Portals#384]
When i try to create a portal, it says an internal error occured

**Comment by BlackDawn187** [comment]
I'm guessing your problem is due to using the updated WorldEdit plugin. I just had the same experience and, Resolved it by updated Multiverse-Portals to Build #773. Which is available here: http://ci.onarandombox.com/job/Multiverse-Portals/lastSuccessfulBuild/artifact/target/

**Comment by dumptruckman** [comment]
Make sure to update Multiverse-Core to the latest dev build also.
