### ISSUE TITLE
Error on Player move event

### ISSUE THREAD

**Issue by MinesanityPvP** [Multiverse/Multiverse-Portals#386]
17.07 00:29:04 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getEconomist()Lcom/onarandombox/MultiverseCore/utils/MVEconomist;

17.07 00:29:04 [Server] INFO at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:105) ~[?:?]

Every time I attempt to move within a portal this error occurs. This happens using the latest build on Jenkins  #723

http://ci.onarandombox.com/job/Multiverse-Portals/

**Comment by dumptruckman** [comment]
You need to use the latest MV-Core as well.

**Comment by MinesanityPvP** [comment]
Wow, I am not sure how I forgot about that. I will test to see if this has been fixed and I will report back

**Comment by dumptruckman** [comment]
Please do. I didn't have a chance to actually test those builds in game.

**Comment by MinesanityPvP** [comment]
Tested all features with latest dev build of MV-Core and MV-Portals. This issue does not persist and all features are working.

**Comment by dumptruckman** [comment]
Thanks!
