### ISSUE TITLE
Minecart Hacks

### ISSUE THREAD

**Issue by DatGoat** [Multiverse/Multiverse-Portals#387]
If a multiverse portal is set up between a creative world, and a survival world, minecarts(with chests) can be pushed from the creative world to survival, giving players a lot of valuable items, can minecarts going through them be disabled??

**Comment by Coding-Architect** [comment]
Set the variable teleportvehicles to:
`teleportvehicles: true`

**Comment by FernFerret** [comment]
Closing as resolved, thanks @Coding-Architect
