### ISSUE TITLE
Modded Server

### ISSUE THREAD

**Issue by KnottyCord** [Multiverse/Multiverse-Portals#388]
I have a modded server and we are not able to do in the deep dark because of multiverse. If we create a portal to the world the portal does not work even if we have all the permision!

**Comment by MinesanityPvP** [comment]
Please use the latest Multiverse-Core version listed in the development builds. These can be found on the Jenkins site! If this does not fix your error. Please paste the error given by console and such!

**Comment by dumptruckman** [comment]
You need to update to the latest developmental builds of Core and Portals available here: http://ci.onarandombox.com/view/Multiverse/
