### ISSUE TITLE
I can't create portal

### ISSUE THREAD

**Issue by mortada2001** [Multiverse/Multiverse-Portals#390]
hi ...
i can't create portal
i selecte the ragion
and im type /mvp create and the name of portal
but dosent work :/ 
plzz i want create portal -_-

**Comment by MinesanityPvP** [comment]
Please use the latest Multiverse-Core version listed in the development builds. These can be found on the Jenkins site!

**Comment by dumptruckman** [comment]
You need to update to the latest developmental builds of Core and Portals available here: http://ci.onarandombox.com/view/Multiverse/
