### ISSUE TITLE
Latest build is causing issues with Vault.

### ISSUE THREAD

**Issue by PsychoNavigator** [Multiverse/Multiverse-Portals#391]
When starting up the server, it appears the MVP plugin is preventing  vault from loading.

http://pastebin.com/G1kfUY1A

**Comment by LightningJimmy** [comment]
I have this issue too, please fix this fast because my server needs Multiverse

**Comment by LightningJimmy** [comment]
The actual latest version fixes this: http://ci.onarandombox.com/job/Multiverse-Portals/723/artifact/target/Multiverse-Portals-2.5.jar
