### ISSUE TITLE
"An internal error has occurred"

### ISSUE THREAD

**Issue by CreepyHulk** [Multiverse/Multiverse-Portals#392]
Hi, I've been having issues with Portals being created believe its an issues with Worldedit compatibility. Every time i use /mvp create command an internal error occurs. i am using Multiverse-Portals Version 2.5-b699 and WorldEdit 6.1 I can't find any recent fixes when i google the problem

**Comment by MinesanityPvP** [comment]
Please give the exact error produced via console to further help your situation from being fixed. Just as a test, I recommend that you update to the latest Multiverse-Core development build! Good luck and I hope the issue does not persist!

**Comment by dumptruckman** [comment]
You need to update to the latest dev builds of Core and Portals available here: http://ci.onarandombox.com/
