### ISSUE TITLE
Portals not working

### ISSUE THREAD

**Issue by Frnee** [Multiverse/Multiverse-Portals#393]
Portals are not working, and THIS monster gets pasted into the console:

02.08 17:10:26 [Server] INFO ... 15 more
02.08 17:10:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
02.08 17:10:26 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
02.08 17:10:26 [Server] INFO at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
02.08 17:10:26 [Server] INFO at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:105) ~[?:?]
02.08 17:10:26 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getEconomist()Lcom/onarandombox/MultiverseCore/utils/MVEconomist;
02.08 17:10:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
02.08 17:10:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-20150729a.jar:git-Spigot-6c9b0a1-de5c261]
02.08 17:10:26 [Server] INFO org.bukkit.event.EventException
02.08 17:10:26 [Server] ERROR Could not pass event PlayerMoveEvent to Multiverse-Portals v2.5-b723

**Comment by MinesanityPvP** [comment]
This issue can be fixed by using the Latest Multiverse-Core version!
