### ISSUE TITLE
Creating a portal won't work with the latest worldedit

### ISSUE THREAD

**Issue by NewBestX** [Multiverse/Multiverse-Portals#394]
I think this error has to do with the way the new worldedit 6.1 works.

http://pastebin.com/HjWJDde9

Can you fix it?

**Comment by Subtleoliver** [comment]
Uppdate to the latest multiverse portals & Core version from Jenkins. http://ci.onarandombox.com/job/Multiverse-Portals/

http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/
