### ISSUE TITLE
PlayerMoveEvent error - Portals stopped working

### ISSUE THREAD

**Issue by agentroop** [Multiverse/Multiverse-Portals#401]
The portals in the hub world of my server have stopped working. I check the log and got the following error:
http://pastebin.com/M6wsbZ9D

I'm running MC Spigot 1.8.8 on a multiverse server. Thanks in advance for any help.
I'm running the latest dev build of Multiverse-Portals.

**Comment by dumptruckman** [comment]
If you're going to update to a dev build of portals you need to do the same for core.
