### ISSUE TITLE
Unable to create portals

### ISSUE THREAD

**Issue by FnarGod** [Multiverse/Multiverse-Portals#403]
I am unable to create portals it just says Internal Error Occured while doing this command and blah blah its really annoying and I honestly have no idea why its happening. Here is my server startup and when I type the commands aswell. Please help me out ASAP <3

26.09 13:03:37 [Server] INFO ... 15 more
26.09 13:03:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
26.09 13:03:37 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
26.09 13:03:37 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
26.09 13:03:37 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
26.09 13:03:37 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
26.09 13:03:37 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
26.09 13:03:37 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
26.09 13:03:37 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
26.09 13:03:37 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
26.09 13:03:37 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:03:37 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b699
26.09 13:03:37 [Server] ERROR null
26.09 13:03:37 [Server] INFO WEAPI
26.09 13:03:37 [Server] INFO FnarGod issued server command: /mvp create TimeRoomToSpawn world
26.09 13:03:27 [Multicraft] OwnerFnarGod ran command Message of the Day
26.09 13:03:27 [Disconnect] User FnarGod has disconnected, reason: unknown
26.09 13:03:27 [Connect] User OwnerFnarGod, IP unknown
26.09 13:03:27 [Server] INFO CONSOLE issued server command: /list 
26.09 13:03:13 [Server] INFO Dibbzie issued server command: /gmc
26.09 13:03:02 [Server] INFO Welcome to UNNAMED SERVER HOST, FnarGod!
26.09 13:03:02 [Multicraft] FnarGod ran command Message of the Day
26.09 13:03:02 [Connect] User FnarGod, IP 65.27.235.111
26.09 13:03:02 [Server] INFO UUID of player FnarGod is 19bd930e-5cb8-4769-bd08-7f52d146e32d
26.09 13:03:01 [Multicraft] Dibbzie ran command Message of the Day
26.09 13:03:01 [Server] INFO Welcome to UNNAMED SERVER HOST, Dibbzie!
26.09 13:03:01 [Connect] User Dibbzie, IP 65.27.235.111
26.09 13:02:56 [Server] INFO UUID of player Dibbzie is 55e6b6e8-f8a2-4ef8-b754-264ac0cebb7b
26.09 13:02:51 [Server] Startup Done (6.033s)! For help, type "help" or "?"
26.09 13:02:51 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
26.09 13:02:51 [Server] INFO 0 - Portals(s) loaded
26.09 13:02:51 [Server] INFO - Version 2.5-b699 Enabled - By Rigby and fernferret
26.09 13:02:51 [Server] INFO Enabling Multiverse-Portals v2.5-b699
26.09 13:02:51 [Server] INFO === ENABLE COMPLETE (Took 498ms) ===
26.09 13:02:50 [Server] INFO === ENABLE START ===
26.09 13:02:50 [Server] INFO Enabling Factions v2.8.0
26.09 13:02:50 [Server] INFO Version 2.5-b691 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--
26.09 13:02:50 [Server] INFO 3 - World(s) loaded.
26.09 13:02:50 [Server] INFO [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b691
26.09 13:02:50 [Server] INFO Enabling Multiverse-Core v2.5-b691
26.09 13:02:50 [Server] INFO Loading region data...
26.09 13:02:50 [Server] INFO Loaded configuration for world 'world_the_end'
26.09 13:02:50 [Server] INFO (world_the_end) Fire spread is UNRESTRICTED.
26.09 13:02:50 [Server] INFO (world_the_end) Lava fire is blocked.
26.09 13:02:50 [Server] INFO (world_the_end) Lighters are PERMITTED.
26.09 13:02:50 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
26.09 13:02:50 [Server] INFO Loaded configuration for world 'world_nether'
26.09 13:02:50 [Server] INFO (world_nether) Fire spread is UNRESTRICTED.
26.09 13:02:50 [Server] INFO (world_nether) Lava fire is blocked.
26.09 13:02:50 [Server] INFO (world_nether) Lighters are PERMITTED.
26.09 13:02:50 [Server] INFO (world_nether) TNT ignition is PERMITTED.
26.09 13:02:49 [Server] INFO Loaded configuration for world 'world'
26.09 13:02:49 [Server] INFO (world) Fire spread is UNRESTRICTED.
26.09 13:02:49 [Server] INFO (world) Lava fire is blocked.
26.09 13:02:49 [Server] INFO (world) Lighters are PERMITTED.
26.09 13:02:49 [Server] INFO (world) TNT ignition is PERMITTED.
26.09 13:02:49 [Multicraft] Skipped 10 lines due to rate limit (30/s)
26.09 13:02:48 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-d97e08b-880a532]
26.09 13:02:48 [Server] INFO at com.earth2me.essentials.geoip.EssentialsGeoIP.onEnable(EssentialsGeoIP.java:34) ~[?:?]
26.09 13:02:48 [Server] INFO at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.<init>(EssentialsGeoIPPlayerListener.java:41) ~[?:?]
26.09 13:02:48 [Server] INFO at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.reloadConfig(EssentialsGeoIPPlayerListener.java:132) ~[?:?]
26.09 13:02:48 [Server] INFO java.lang.NoClassDefFoundError: com/maxmind/geoip/LookupService
26.09 13:02:48 [Server] ERROR Error occurred while enabling EssentialsGeoIP vTeamCity (Is it up to date?)
26.09 13:02:48 [Server] INFO Enabling EssentialsGeoIP vTeamCity
26.09 13:02:48 [Server] INFO Enabling EssentialsChat vTeamCity
26.09 13:02:48 [Server] INFO Permissions listed in as player-commands will be given to all users.
26.09 13:02:48 [Server] INFO Essentials: Using config file enhanced permissions.
26.09 13:02:48 [Server] INFO Using locale en_US
26.09 13:02:48 [Server] INFO Using locale en_US
26.09 13:02:48 [Server] INFO 1.8.8-R0.1-SNAPSHOT
26.09 13:02:48 [Server] INFO git-Spigot-d97e08b-880a532 (MC: 1.8.8)
26.09 13:02:48 [Server] INFO Bukkit version format changed. Version not checked.
26.09 13:02:48 [Server] INFO Enabling Essentials vTeamCity
26.09 13:02:47 [Server] INFO Enabling AntiCheatPlus v2.1.4
26.09 13:02:47 [Server] INFO Enabled! Config Loaded! Kicking!
26.09 13:02:47 [Server] INFO Enabling NoSwear v6.2
26.09 13:02:47 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
26.09 13:02:47 [Server] INFO WEPIF: Using the Bukkit Permissions API.
26.09 13:02:47 [Server] INFO Enabling WorldEdit v6.1;no_git_id
26.09 13:02:47 [Server] INFO Preparing start region for level 2 (Seed: 7852392281468088861)
26.09 13:02:46 [Server] INFO Preparing start region for level 1 (Seed: 7852392281468088861)
26.09 13:02:46 [Multicraft] Skipped 83 lines due to rate limit (30/s)
26.09 13:02:45 [Server] INFO Structure Info Saving: true
26.09 13:02:45 [Server] INFO Random Lighting Updates: false
26.09 13:02:45 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
26.09 13:02:45 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
26.09 13:02:45 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
26.09 13:02:45 [Server] INFO NetherWart Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Wheat Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Sapling Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Pumpkin Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Mushroom Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Melon Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Cane Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Cactus Growth Modifier: 100%
26.09 13:02:45 [Server] INFO Nerfing mobs spawned from spawners: false
26.09 13:02:45 [Server] INFO Replace Blocks: [1, 5]
26.09 13:02:45 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
26.09 13:02:45 [Server] INFO Engine Mode: 1
26.09 13:02:45 [Server] INFO Anti X-Ray: true
26.09 13:02:45 [Server] INFO Mob Spawn Range: 4
26.09 13:02:45 [Server] INFO -------- World Settings For [world] --------
26.09 13:02:45 [Server] INFO Preparing level "world"
26.09 13:02:45 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
26.09 13:02:45 [Server] INFO === ENABLE COMPLETE (Took 104ms) ===
26.09 13:02:45 [Server] INFO Setup of IdUtil took 6ms.
26.09 13:02:45 [Server] INFO Saving Cachefile...
26.09 13:02:45 [Server] INFO Loading Registry datas...
26.09 13:02:45 [Server] INFO Loading Onlineplayer datas...
26.09 13:02:45 [Server] INFO Loading Cachefile datas...
26.09 13:02:45 [Server] INFO === ENABLE START ===
26.09 13:02:45 [Server] INFO Enabling MassiveCore v2.8.0
26.09 13:02:43 [Server] INFO Enabling mcMMO v1.5.00-b3547
26.09 13:02:43 [Server] INFO Loading Multiverse-Portals v2.5-b699
26.09 13:02:43 [Server] INFO Loading Factions v2.8.0
26.09 13:02:43 [Server] INFO TimeUnit.MILLIS_PER_MINUTE: 60000
26.09 13:02:43 [Server] INFO Loading MassiveCore v2.8.0
26.09 13:02:43 [Server] INFO Loading Multiverse-Core v2.5-b691
26.09 13:02:43 [Server] INFO Loading WorldGuard v6.1
26.09 13:02:43 [Server] INFO Loading EssentialsSpawn vTeamCity
26.09 13:02:43 [Server] INFO Loading mcMMO v1.5.00-b3547
26.09 13:02:43 [Server] INFO Loading EssentialsGeoIP vTeamCity
26.09 13:02:43 [Server] INFO Loading EssentialsChat vTeamCity
26.09 13:02:43 [Server] INFO Loading Essentials vTeamCity
26.09 13:02:43 [Server] INFO Loading AntiCheatPlus v2.1.4
26.09 13:02:43 [Server] INFO Loading NoSwear v6.2
26.09 13:02:43 [Server] INFO Loading WorldEdit v6.1;no_git_id
26.09 13:02:43 [Server] INFO Set PluginClassLoader as parallel capable
26.09 13:02:43 [Server] INFO Using epoll channel type
26.09 13:02:43 [Server] INFO Starting Minecraft server on 167.114.100.223:25580
26.09 13:02:43 [Server] INFO Generating keypair
26.09 13:02:43 [Server] INFO Debug logging is disabled
26.09 13:02:43 [Server] INFO Using 4 threads for Netty based IO
26.09 13:02:43 [Server] INFO Server Ping Player Sample Count: 12
26.09 13:02:43 [Server] INFO This server is running CraftBukkit version git-Spigot-d97e08b-880a532 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
26.09 13:02:43 [Server] INFO Default game type: SURVIVAL
26.09 13:02:43 [Server] INFO Loading properties
26.09 13:02:43 [Server] INFO Starting minecraft server version 1.8.8
26.09 13:02:38 [Server] INFO Loading libraries, please wait...
26.09 13:02:37 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 24921
26.09 13:02:37 [Multicraft] Updating eula.txt file
26.09 13:02:37 [Multicraft] Loaded config for "Mod: Spigot 1.8.8"
26.09 13:02:37 [Multicraft] Starting server!

**Comment by dumptruckman** [comment]
Update Core and Portals.
