### ISSUE TITLE
portals not teleporting right

### ISSUE THREAD

**Issue by StarShine13** [Multiverse/Multiverse-Portals#405]
everything loads in properly, you can use all the commands, but after having the portals all set up and the destination set no matter what when you walk through the portal it teleports me to what I have set as my newbie spawn and I fall through the world (though the world im doing this in is a void world)

im using the most up-to-date portals and core for 1.8

**Comment by FernFerret** [comment]
It sounds like this could be the Safe-T-Teleporter trying to be too smart, but more details would be good.

**Comment by FernFerret** [comment]
Closing as inactive (> 7 days without comment from submitter) and we're trying to keep up with idle issues better.

If you're still having issues, please post an update and we'll reopen this!  :+1:
