### ISSUE TITLE
price and currency

### ISSUE THREAD

**Issue by bud-lwos** [Multiverse/Multiverse-Portals#406]
This is an assistance request.  I also posted this question on Curse.

I have a portal set up to charge 1 diamond per use. It works fine -- takes the diamond from the player's inventory as expected.  

But where does the diamond go?  I would like it to go to the owner of the portal. 

I am not currently using any economy plugin. Will I need to?

Thanks

**Comment by dumptruckman** [comment]
Unfortunately our portals do not know who the owner is so that kind of complicates things. You would need some kind of add on plugin to add this functionality.

**Comment by bud-lwos** [comment]
Thanks for the reply.  I'm thinking that what I would like to happen is probably not going to happen. 

I am now curious, however, about what happens when I modify a portal to set the owner. Does it still not know who the owner is?

**Comment by dumptruckman** [comment]
No. If you try that I believe it will tell you that the property was NOT set. You can only set properties that are predefined by the plugin.

Unfortunately it's quite likely this feature won't be added. A separate plugin would need to be made that tracks the portal owner and the payments for using the portal. I *believe* MV-Portals throws events for these things so it should be doable.
