### ISSUE TITLE
Incompatible With Worldedit 6.0

### ISSUE THREAD

**Issue by ak6865** [Multiverse/Multiverse-Portals#409]
One day after updating worldedit and starting up my server multiverse portals seemed to have a problem with worldedit. After awhile browsing forums i figured out it was something with the new update. I had to downgrade worldedit again to get it working.

Could you please get multiverse-portals compatible with worldedit?

**Comment by Subtleoliver** [comment]
It is. You need to update to the latest build. 

Skickat från min iPad

**Comment by FernFerret** [comment]
So... is this resolved?

**Comment by dumptruckman** [comment]
Yes.
