### ISSUE TITLE
Players can get the water from Fill Water Portal

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Multiverse/Multiverse-Portals#411]
Players are so unfair they steal the water from Portal and i don't have an idea to prevent it!

**Comment by FernFerret** [comment]
Something like this is probably best left for a world protection plugin, ie: preventing players from taking water. I don't believe it belongs here in the portals tracker.

**Comment by FernFerret** [comment]
Going to mark this as won't fix, since it's not part of Multiverse's Scope
