### ISSUE TITLE
Update to 1.9

### ISSUE THREAD

**Issue by ThunderGemios10** [Multiverse/Multiverse-Portals#417]
@dumptruckman Can you please update this to Spigot 1.9?

**Comment by FernFerret** [comment]
Please see issue https://github.com/Multiverse/Multiverse-Portals/issues/415. If this is not the same issue you're having, please[ post a bug report with more details](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug).

Closing for now, please reopen if you have some stack traces or whatnot.
