### ISSUE TITLE
Random portal exit

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Portals#42]
it would be great to have a portal that teleports players to a random place in a defined area or randomly choose between a set of portals (or better https://github.com/Multiverse/Multiverse-Portals/issues/41 :)

**Comment by aolko** [comment]
what's the command (Arg) for random tp again?

**Comment by CaszGamerMD** [comment]
bump for solution?

**Comment by joex92** [comment]
so how do I setup a random exit location?

**Comment by FernFerret** [comment]
Mains commit says:

Usage:
"rp:portal1:portal2:portal3"

**Comment by joex92** [comment]
ok, so I have to create portals for it to work?
