### ISSUE TITLE
Portals not working

### ISSUE THREAD

**Issue by GunnerFRC** [Multiverse/Multiverse-Portals#424]
Hello,
I have correctly installed MVP and its prerequisites but It will not let me create portals, saying "An Internal Error occurred". Most guides say downgrade my world edit or remove it, but after trying this still happens, even with world edit removed. I am using MVP 2.4 (2.5 does not work at all).

To note:
DO NOT SAY I NEED TO UPDATE TO 2.5 AND CLOSE THIS. I just stated that it does not work /\. I don't know why 2.5 does not work for me, but when I install it the log says "Outdated MV Core", even though I'm using the latest version. This article has been re-opened because someone did not read the entire article and closed this. 
Log:
04.04 13:04:47 [Server] INFO GunnerBones issued server command: /mvp create Cportal 04.04 13:04:47 [Server] ERROR null 04.04 13:04:47 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548 04.04 13:04:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:624) ~[craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1298) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1158) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77] 04.04 13:04:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77] 04.04 13:04:47 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.MVPortal.addToUpperLists(MVPortal.java:157) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.MVPortal.init(MVPortal.java:92) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:61) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.MVPortal.<init>(MVPortal.java:219) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.utils.PortalManager.addPortal(PortalManager.java:126) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:62) ~[?:?] 04.04 13:04:47 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?] 04.04 13:04:47 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?] 04.04 13:04:47 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?] 04.04 13:04:47 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?] 04.04 13:04:47 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?] 04.04 13:04:47 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.9.jar:git-Bukkit-f326992] 04.04 13:04:47 [Server] INFO ... 15 more

Does someone know a fix? Thanks, Gunner

**Comment by dumptruckman** [comment]
Please stop spamming tickets. You can continue to comment on the closed tickets. If you want to use Multiverse on 1.9, you MUST use the latest dev builds of Multiverse-Portals **AND** Multiverse-Core. Install BOTH of them, just using the latest dev portals doesn't work because as you said it says your MV-Core is out of date. The latest dev build of Multiverse-Portals works with World Edit 6.0 or newer.

**Comment by brayjamin** [comment]
THIS IS FUCKING RETARDED
