### ISSUE TITLE
Factions support

### ISSUE THREAD

**Issue by Genesis2001** [Multiverse/Multiverse-Portals#427]
As far as I can tell, I don't see Factions support. Is it possible to support factions and have faction-only portals maybe? Or have the faction leader be able to designate a portal as a faction-internal portal or available to the public. :)

**Comment by FernFerret** [comment]
Sorry, this isn't something that I have a desire or time to do. If you know someone that would like to open a pull-request and have it implemented in a way such that users do not have to have factions installed, we'd be more than willing to accept said pull-request.

Thanks!
