### ISSUE TITLE
[Suggestion] Make portals not bring people to world spawns

### ISSUE THREAD

**Issue by Tzzzt123** [Multiverse/Multiverse-Portals#428]
Hi Multiverse-Team,
Can i make a Suggestion to get the possibility to make Multiverse-Portals bring people to the last place they were in the world?
Thank You
Tzzzt123

**Comment by Tzzzt123** [comment]
please answer

**Comment by Sammot** [comment]
This NEEDS to be a thing

**Comment by blazem** [comment]
Bumping - did this become a feature / is there code available to make this happen?

**Comment by benwoo1110** [comment]
Actually, this is a responsibility of multiverse-inventories, mv-portal shouldn't be storing player locations.

See: https://github.com/Multiverse/Multiverse-Core/wiki/Shares-List-(Inventories)#last_location

If you think last location isn't working as excepted or want to request feature on it, please do so at https://github.com/Multiverse/Multiverse-Inventories/issues
