### ISSUE TITLE
Safeteleport forced

### ISSUE THREAD

**Issue by SamuraiKal** [Multiverse/Multiverse-Portals#43]
I'm trying to create a destination that causes people to fall into a chasm.  I've turned safeteleport to false but it's still giving me the error "No safe locations found!" when I try to walk through the portal.

**Comment by XGNRen** [comment]
it's been a long long time since anyone has been here and I'm sorry for re-opening this thread, but I'm also having this issue in 2023. What do you mean by exact destination?

**Comment by XGNRen** [comment]
Nevermind got it covered, just gonna leave this here for anyone who doesn't figure it out:

Run the commands /mvp select (PortalName) and then /mvp modify dest e:(WorldName):(coordinates)
For example in my case: /mvp select SpawnToSpaceArena and then /mvp modify dest e:SpaceArena:0,160,-2

**Comment by Phantom811** [comment]
hello if you could help me with the multiverse portals than that would be wonderful, beacus i just cant figure it out how to turn of safe teleport
