### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Chickency** [Multiverse/Multiverse-Portals#430]
Whenever I do /mvp create creative, it has an internal error. The Console showing the Error is here:
http://pastebin.com/SVAPw4SL. What do I do?

Thank you,
Chickency

**Comment by FernFerret** [comment]
Oh interesting...

Can you post the link generated from `/mv version -g` for me?

**Comment by Chickency** [comment]
Here is the Console. http://pastebin.com/FhwEJkdu

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
