### ISSUE TITLE
Losing combat tag when going through portals?

### ISSUE THREAD

**Issue by tehrenderr** [Multiverse/Multiverse-Portals#431]
Title says it all, if you are in combat and go through a portal, you lose your combat tag. I am using combattagplus.

**Comment by FernFerret** [comment]
I have a feeling that this isn't us *but* I could be wrong on this one. In theory we're just using the teleport APIs provided by the server, but if there's a flag to keep that around, we should set it.

I'll have to delve into the documentation. Do you lose combat tags if you just do a `/tp PLAYER` that's in another world?

**Comment by tehrenderr** [comment]
I wouldn't be able to test that since players can't be teleported in combat.

**Comment by tehrenderr** [comment]
Did you find anything in the documentation?

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
