### ISSUE TITLE
Portal Create Not Working

### ISSUE THREAD

**Issue by tyschnoor** [Multiverse/Multiverse-Portals#434]
When I do;

> /mvp create ToMap e:world:-177.782,64,346.263

This pops up;

> An internal eror occured while attempting to perform this command

Please help me!!!!!!

**Comment by FernFerret** [comment]
If you're seeing that, a traceback has been dumped to your logs. Please find that and post it here. Thanks.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
