### ISSUE TITLE
An internal errror [1.10]

### ISSUE THREAD

**Issue by jayisback12** [Multiverse/Multiverse-Portals#435]
Hi ive had this issue where im trying create protals on 1.10 i dont know if it the update or the plugin i would love if this could be fix so i can connect up a hub thanks guys here few little bits and bobs
- console error without debug http://pastebin.com/KGjFHw3j
- with debug http://pastebin.com/72a9xepS

**Comment by awesomebing1** [comment]
Same issue + fix as #429.
