### ISSUE TITLE
Players end 1 block underground, wrong direction

### ISSUE THREAD

**Issue by SentryTheDefiant** [Multiverse/Multiverse-Portals#436]
some portals result in players screens flashing the correct destination, then teleporting them again to the same location, 1 block down, facing the wrong way. 

This happens whether the destination is Worldname   w:worldname   w:worldname:n/s/e/w,  "dest here". This happens whether adjustspawn is on or off.  I've checked that the destination for the portals matches the world spawn.    /mvtp brings players to the correct location, with the correct facing. 

the console gives a "could not pass player move event to multiverse portals" error. Does not give this error when correctly teleporting players.

**Comment by Spearhartt** [comment]
I'm also having this issue. I'm looking into it now. When I recreate the situation on a clean server environment I am not having the same issue. It is likely that there is a plugin conflict occurring. Will add more as I discover what's going on.
