### ISSUE TITLE
Same internal problem

### ISSUE THREAD

**Issue by GodMorduk** [Multiverse/Multiverse-Portals#440]
Hello to all of you.

My apology for my bad English, I'm not a native speaker of that language. 

So, there are one very important problem, connected to the new versions of WorldEdit. Problem was described here #429.

So, latest version SNAPSHOT from [here](https://ci.onarandombox.com/job/Multiverse-Portals/) is not working for me. As I see, then I type "/mv portal" there are only one command - check. All others (wand, create), not working at all.

I guess the reason of that is because that SNAPSHOT version is for 1.8.9 or smth like this. 

Can you, please, create a fixed version of MV Portals, which could work with World Edit 6.0+ on 1.7.10? 

Best wishes, 
Naks.

**Comment by cjburkey01** [comment]
Have you tried 2.5-b699? Here's a link: https://dev.bukkit.org/projects/multiverse-portals/files/771760

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
