### ISSUE TITLE
Error With Random Portals (rp: syntax)

### ISSUE THREAD

**Issue by e1337geek** [Multiverse/Multiverse-Portals#447]
We are receiving the following error when attempting to use the syntax given in the commit to solve issue #42. 

`22.01 19:49:53 [Server] ERROR Could not pass event PlayerMoveEvent to Multiverse-Portals v2.5-b725
22.01 19:49:53 [Server] INFO org.bukkit.event.EventException
22.01 19:49:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:609) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
22.01 19:49:53 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
22.01 19:49:53 [Server] INFO Caused by: java.lang.IllegalArgumentException: bound must be positive
22.01 19:49:53 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_111]
22.01 19:49:53 [Server] INFO at com.onarandombox.MultiversePortals.destination.RandomPortalDestination.getLocation(RandomPortalDestination.java:46) ~[?:?]
22.01 19:49:53 [Server] INFO at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:75) ~[?:?]
22.01 19:49:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
22.01 19:49:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
22.01 19:49:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
22.01 19:49:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-aad97c4-4602331]
22.01 19:49:53 [Server] INFO ... 15 more`

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
