### ISSUE TITLE
Portal Wont Create

### ISSUE THREAD

**Issue by Destroyer5266** [Multiverse/Multiverse-Portals#450]
When i try to make a multiverse portal it says "Multiverse doesn't know about (Map im using) yet
Type /mv import ? for help! and i do that and all i get is the commands to import a world and the world that im making the portal on isnt imported its the main world

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
