### ISSUE TITLE
spigot 1.12 pre errors

### ISSUE THREAD

**Issue by ardentcrest** [Multiverse/Multiverse-Portals#455]
Errors in 1.12 pre spigot.

09:51:59 [SEVERE] Error occurred while enabling Multiverse-Portals v2.5.0-SNAPSHOT-b748 (Is it up to date?)
09:51:59 java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
09:51:59 	at com.onarandombox.MultiversePortals.MultiversePortals.loadConfig(MultiversePortals.java:245) ~[?:?]
09:51:59 	at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:132) ~[?:?]
09:51:59 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
09:51:59 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-429b0e3-5195487]
09:51:59 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Jeppa** [comment]
same here : spigot 1.12 pre5

**Comment by FernFerret** [comment]
Closing in favor of #457.

I'll see about fixing this today/tomorrow.
