### ISSUE TITLE
Interactions with chest_minecarts and empty minecarts

### ISSUE THREAD

**Issue by wapjoe** [Multiverse/Multiverse-Portals#460]
Hello,

Please excuse me if my English is not so good, I use the google translator. ;-)

Until now, I use the plugin "Stargate 0.8.1", but since I can not teleport chest_minecarts, I've become aware of your plugin. With "MV2 Portals" it is also not possible, but you are more active than the Stargate developers. (Btw. both plugins can work very well in parallel.)

I would like to transport items with chest_minecarts to other worlds, is there a chance to realize with "MV2 Portals"? As soon as a chest_minecart, whether full or empty, goes through the portal, it changes every second (cooldown) between the portals and can only be stopped by destroying the underlying block. Stuffed chest_minecarts also lose their items.

The teleporting of empty minecarts is also not possible, it changes like the chest_minecarts between the portals. But that is not so important.

Another question: The option teleportnonplayers in the portals.yml is set to "false" for each portal, which causes this option and can this option be set to "true" by default?

Another problem: If the portal is two blocks wide, I land at the target always in the middle of the two blocks, when I drive with the minecart I am not on the rails, but between both tracks. At the moment I help myself, in which I make the portal a block wide and build a portal per direction.

Is it possible to integrate my wishes into one of the next versions?

Best regards
Jörg (wapjoe)

**Comment by wapjoe** [comment]
@dumptruckman may you can help?

**Comment by wapjoe** [comment]
No support = Closed and uninstall the plugin, I don't need your plugin without support!

**Comment by dumptruckman** [comment]
Good thing you're not paying for it amirite?!

**Comment by wapjoe** [comment]
Sorry my comment was a bit hard. It's a greate app, but i can't use it. The Project where I like to using it, is now forgotten.
