### ISSUE TITLE
Portals Not Teleporting Correctly

### ISSUE THREAD

**Issue by GingerFrog23** [Multiverse/Multiverse-Portals#462]
I have an issue when a player uses a portal it works the first couple of times but like the 3+ time it is used the player either gets teleported one block below the ground or just completely underground suffocating. It is weird because it works fine in the beginning and just randomly starts messing up like that. 

Thanks for trying to help
Colin

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
