### ISSUE TITLE
SIGNPORTALS not working at all

### ISSUE THREAD

**Issue by Mowhok** [Multiverse/Multiverse-Portals#464]
hello, i installed the core and singportals like in all the tutorialvideos but the [mv] doesnt turn blue and i cant port

Can you fix this please for 1.12 ?

**Comment by Jadiction** [comment]
Closing ticket because it's unrelated to Multiverse-Portals. Try updating to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket (IN Multiverse-SignPortals) if this issue persists.
