### ISSUE TITLE
Multiverse Portals not compatible with Multiverse Adventure? 

### ISSUE THREAD

**Issue by Woppow1** [Multiverse/Multiverse-Portals#466]
Hello, today on my server I link two portals using Multiverse Portals in different worlds and then converted one of the portals world to an adventure world with /mva enable (WorldName) using Multiverse Adventure. After this when I tried to travel through the portal it wouldn't work, please help.

**Comment by Woppow1** [comment]
Again, I would love any help you guys would have.

**Comment by Jadiction** [comment]
Sorry, Multiverse-Adventure is an abandoned plugin as of right now and I'm unsure if it's planned to be updated.
