### ISSUE TITLE
World Spawn Coords Wont Save!

### ISSUE THREAD

**Issue by MezzaDev** [Multiverse/Multiverse-Portals#468]
Hi. My spawn i built was accidently made so the player has to spawn facing east. I am changing my coords but when i save and reload the server, they reset back. Ive even tried /mvm set spawn and it says its included the pitch and yaw, but when i save all and reload it hasnt saved. I have essentials on the server, and ive set the essentials spawn priority to lowest and still nothing. Please help me with this issue as the spawn will crash the server if i rotate it!

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
