### ISSUE TITLE
Price and currency

### ISSUE THREAD

**Issue by Doctor4711** [Multiverse/Multiverse-Portals#471]
The portals I create work just fine and go where i direct them, however I do not seem able to set price or currency. 
If i use the /mvp modify command to set either "curr" or "price" for a specific portal it will confirm that said portal now has the price/currency set at whatever I entered...however if I then go through said portal without the "price item" in my inventory the portal works anyways and nothing is subtracted. It does not seem to block me from using it whether I have the currency to pay it or not despite informing me the modify price command was a success
I have vault on my server and i think a "bagofgold" plugin for money....but the portals do the same thing whether i set the price to be money or blocks

**Comment by Rocologo** [comment]
To Doctor4711, if you use my BagOfGold plugin

https://www.spigotmc.org/resources/bagofgold.49332/

The Bags is handled as money, and I have tested price on the portals and it seems to work fine.
