### ISSUE TITLE
Error on Spigot 1.13.1 - java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection

### ISSUE THREAD

**Issue by robotnikthingy** [Multiverse/Multiverse-Portals#480]
I get this error when trying to use the /mvp create command on spigot 1.13.1 and using the latest build of Worldedit from their build server

https://hastebin.com/urejudiyuj.sql

**Comment by Jadiction** [comment]
Duplicate of https://github.com/Multiverse/Multiverse-Portals/issues/475
