### ISSUE TITLE
Nether Portal blocks facing north/south when placing a portal facing east/west

### ISSUE THREAD

**Issue by Berenvonbaggins** [Multiverse/Multiverse-Portals#481]
This issue has come up many times. I will place a portal (size varies) facing north and south, and I will light it with a flint and steel and the blocks will appear facing north and south. But when I repeat the process, only the portal is facing east and west, the portal blocks will still face north and south. I'm not sure if there's a command or there's something in the config.yml file, but this issue is very important. I've attached some pictures for reference:
![2018-09-03_17 06 21](https://user-images.githubusercontent.com/42331694/45002451-38f2df00-af9c-11e8-9493-287cd1105eb3.png)
![2018-09-03_17 07 14](https://user-images.githubusercontent.com/42331694/45002452-398b7580-af9c-11e8-9039-6b7be9468898.png)

**Comment by Jadiction** [comment]
Unrelated to MV-Portals.
