### ISSUE TITLE
multiverse portals snapshot 2.52 internal error

### ISSUE THREAD

**Issue by sirtuftcat** [Multiverse/Multiverse-Portals#482]
I have a gameservers account with multiverse portals and multiverse core.. portals isn't working for some reason.. I keep getting a internal error message when trying to use it.. the server staff looked at my consol and they think theres a bug with the plug in.. do you know if the latest portals version is compatible with multiverse 2.60 or if theres something else I need? I don't have world edit installed and I don't think I have any builds installed.. theres been mention about maybe needing dev builds?? but im new at all this

**Comment by sirtuftcat** [comment]
also heres the site I got the jar files from 
https://ci.onarandombox.com/job/Multiverse-Core/

**Comment by sirtuftcat** [comment]
console information on error
8‎:‎47‎:‎50‎ ‎PM CONSOLE: [INFO] sirtuftcat issued server command: /mvp wand
‎8‎:‎47‎:‎50‎ ‎PM CONSOLE: ERROR]: null 
‎8‎:‎47‎:‎50‎ ‎PM CONSOLE: exception executing command 'mvp' in plugin Multiverse-Portals v2.5.2-SNAPSHOT-b765
‎8‎:‎47‎:‎50‎ ‎PM CONSOLE: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(II)V

**Comment by Jadiction** [comment]
Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
