### ISSUE TITLE
Portals build - http://repo.bukkit.org/content/repositories/public not available

### ISSUE THREAD

**Issue by mark-psl** [Multiverse/Multiverse-Portals#483]
I've followed the readme directions for building the Portals .jar and am getting the following when I try to build via Maven.

> [ERROR] Failed to execute goal on project Multiverse-Portals: Could not resolve dependencies for project com.onarandombox.multiverseportals:Multiverse-Portals:jar:2.5.2-SNAPSHOT: Could not transfer artifact org.bukkit:bukkit:jar:1.3.2-R0.2 from/to Official Bukkit (http://repo.bukkit.org/content/repositories/public): repo.bukkit.org: Name or service not known: Unknown host repo.bukkit.org: Name or service not known -> [Help 1]

I have set the SPIGOT_BASE via an export to the location of the BuildTools.jar after successfully building Bukkit/Craftbukkit/Spigot .jar files.

Thoughts?

**Comment by Jadiction** [comment]
Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
