### ISSUE TITLE
Curious as to where stable builds are and dev builds are?

### ISSUE THREAD

**Issue by axemwa** [Multiverse/Multiverse-Portals#485]
Curious as to where stable builds are and dev builds are. Are the stable builds on spigotmc or bukkitdev as I noticed that multiverse on spigot was last updated in 2016, multiverse on bukkitdev was last updated in 2017 and the multiverse in this link https://ci.onarandombox.com/job/Multiverse-Core/ was last updated in 2018

**Comment by FernFerret** [comment]
I've transferred your issue to Portals since Core does not use WorldEdit.
