### ISSUE TITLE
Portal spawn location inconsistent.

### ISSUE THREAD

**Issue by Alex-DataSIM** [Multiverse/Multiverse-Portals#502]
MV-P version: 2.5.2 SNAPSHOT
Spigot Paper V564

Spawn locations are inconsistent after being teleported by a portal. 

I've setup two portals that go to specific world spawns:
/mvp create SpawnToEarth w:earth
/mvp create EarthToSpawn w:spawn

Once a player enters the portal and gets teleported, the exact location the player spawns at varies by around 2-5 blocks.
The players direction also seems to be selected at random.
No errors are being thrown in the console and I couldn't find anything regarding this in the config.

I am wondering if this is intended behaviour or a bug. Do any other plugins mess with the teleport location?  EssentialsX maybe?

If any more info is needed, let me know and I will do my best to provide it.

**Comment by Jadiction** [comment]
I was unable to reproduce this.
Can you try without other plugins (maybe locally and backup before doing so)?

**Comment by Jadiction** [comment]
Oops, didn't mean to close just yet.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
