### ISSUE TITLE
Error when using /mvp wand

### ISSUE THREAD

**Issue by TechHax** [Multiverse/Multiverse-Portals#508]
I am getting and error when using the in game command /mvp wand. In the game it gives the error
`An internal error occurred while attempting to preform this command `

and in the servers logs it gives the following

`31.05 19:14:36 [Server] ERROR null
31.05 19:14:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5.0-b751
31.05 19:14:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
31.05 19:14:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
31.05 19:14:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(II)V
31.05 19:14:36 [Server] INFO at com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:59) ~[?:?]
31.05 19:14:36 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
31.05 19:14:36 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
31.05 19:14:36 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
31.05 19:14:36 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
31.05 19:14:36 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]
31.05 19:14:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
31.05 19:14:36 [Server] INFO ... 15 more
`

I dont belive this error is on my end. I saw some people were having issues when they had world eddit installed but I dont have world edit. My mc server is spigot 1.13.2.

**Comment by Jadiction** [comment]
Update to the latest dev build version of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists.
