### ISSUE TITLE
An internal Error Occurred while attempting to perform this command

### ISSUE THREAD

**Issue by xXMrMoose** [Multiverse/Multiverse-Portals#510]
I am running a server and am trying to set up portals. I can't seem to get my /mvp wand command to work because it says "An internal Error Occurred while attempting to perform this command".  I looked it up and it says something to do with worldedit 6.0, the server I am running uses 7.0 but I still removed it and restarted the server to make sure it wasn't the issue.  After restarting it did nothing and gave the same internal error message in chat. 

Any ideas on how to fix?

Console Logs \/

> [17:28:50] [Server thread/ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5.0-b751at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:686) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1619) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1473) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$2664.0000000004062A10.run(Unknown Source) ~[?:?]at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:853) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:846) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:829) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:770) [craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.NullPointerExceptionat com.onarandombox.MultiversePortals.commands.WandCommand.runCommand(WandCommand.java:53) ~[?:?]at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:358) ~[?:?]at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[craftbukkit-1.14.2-R0.1.jar:git-Bukkit-f2757f9]... 18 more

>

**Comment by kristaelena** [comment]
Having the same problem! I updated the permissions and even the people who are OP aren't allowed to use the command. Help!!!!!!

**Comment by Jadiction** [comment]
You're using an outdated version of Multiverse-Portals. Currently, this is the latest: https://ci.onarandombox.com/job/Multiverse-Portals/797/

**Comment by Jadiction** [comment]
Going to assume this is solved - closing the ticket. If you're still having issues, please don't hesitate to make another ticket or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
