### ISSUE TITLE
An internal error occured when creating a portal

### ISSUE THREAD

**Issue by samidont0817** [Multiverse/Multiverse-Portals#511]
https://pastebin.com/ikuwvKeW
I am trying to create a portal to a multiverse world and it is not working.
MC Version 1.13.2
PaperSpigot 564
Version of Multiverse portal 3.0.0

**Comment by dumptruckman** [comment]
The version of WorldEdit you're using is not compatible with your Multiverse-Portals version

**Comment by samidont0817** [comment]
We have FastASyncWorldEdit. Does it have to be actual WorldEdit?

**Comment by dumptruckman** [comment]
It just needs to be the right version. Not sure which that would be.

**Comment by samidont0817** [comment]
Hmm alright~ Ill try that. Thanks~

**Comment by Jadiction** [comment]
Going to assume this is solved - closing the ticket. If you're still having issues, please don't hesitate to make another ticket or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
