### ISSUE TITLE
Version 1.14.4 problem plugin version 4.0.0 

### ISSUE THREAD

**Issue by PROZACTv** [Multiverse/Multiverse-Portals#517]
[Multiverse-Core] "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman]

**Comment by Jadiction** [comment]
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/2000 and this belongs to MV-Core.
