### ISSUE TITLE
1.14 [Server thread/ERROR]: Could not load 'plugins\Multiverse-Portals-4.0.0.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by RETZ1LLA** [Multiverse/Multiverse-Portals#527]
Several people have been commenting on the page thread about this error message

 [Server thread/ERROR]: Could not load 'plugins\Multiverse-Portals-4.1.0.jar' in folder 'plugins'

https://www.spigotmc.org/resources/advanced-portals.14356/

Download this file and run server :)

**Comment by OGDarkAnxiety** [comment]
I have the same problem please help

**Comment by Jadiction** [comment]
Try 4.1.0 or 4.1.1 (dev build), currently, it's what I'm using for 1.14 with no issues. 

https://dev.bukkit.org/projects/multiverse-portals/
