### ISSUE TITLE
Portal teleporting player facing the wrong way

### ISSUE THREAD

**Issue by CosmicQueso** [Multiverse/Multiverse-Portals#529]
Problem:
Multiverse-Portals is making a portal face an undesired direction (south) instead of the way the portal should face (west).

Context:
I have a portal (border made from obsidian, portal is water), that faces West. Using WorldEdit, I make a selection for the area inside the border of the portal. I type in this command to create the portal: /mvp create "endtutorialportal" e:"Biome Bundle":"11803.5,201.0,6645.5" Then when walking through the portal, (walking through fading West) I am teleported to the location (on another world) facing South which is not the desired location. I have looked everywhere but cannot find an answer to my problems.

What I have tried:
•  Rotating the portal 90° Clockwise, same problem occurred.
• Using flint and steel to create portal that uses the "Nether Portal" look, same problem occurred, nether portal created after being teleported to location.
•  Looking on the Multiverse-Core and Multiverse-Portal Wiki, no answers to be found.

**Comment by xManInWhitex** [comment]
Have you tried going to the coordinate where the player should be teleported to and using the following command?

_/mvpm dest here_

 (When executing the command, look in the direction the player should look after being teleported. You have to select the entrance portal before using the command. _/mvp select endtutorialportal_)

**Comment by Jadiction** [comment]
Closing old ticket. Make sure to update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
