### ISSUE TITLE
World names bugged

### ISSUE THREAD

**Issue by swat077** [Multiverse/Multiverse-Portals#540]
Hey, so I downloaded this plugin and wanted to copy my existing world so I could have 1 for pvp and 1 for normal survival. Now I have the problem that all the worlds are called 'world' and I can't tp between them. When I change their names, aliases, color, .. in the config and restart the server then, all the world still keep the same name and when I check everything went back to normal in the config.
How can I solve this problem ? 
Thank you in advance !!
![image](https://user-images.githubusercontent.com/62989016/78119214-6027c180-7408-11ea-8f2f-a8f39d218f3b.png)

**Comment by benwoo1110** [comment]
Unrelated to multiverse portals. Report it in multiverse core.

**Comment by swat077** [comment]
Oh my bad, can be deleted then
