### ISSUE TITLE
I can't use Multiverse Portals on a 1.8.8 server

### ISSUE THREAD

**Issue by thecoolersevs** [Multiverse/Multiverse-Portals#542]
Hi, I run a 1.8.8 server for me and my friends and can't get Multiverse Portals to work. I have Multiverse Core 2.5 and Multiverse NetherPortals 2.5 but whenever I do /mvp wand it just comes back with "unknown command. Type "/help" for help." I've looked around for why it won't work and came across someone saying disable WorldEdit use /mvp wand and then re-enable WorldEdit, that didn't work for me either. Am I missing something or doing something wrong?

**Comment by benwoo1110** [comment]
You need to install multiverse-Portals: https://dev.bukkit.org/projects/multiverse-portals/files/898528

On how to create portals: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Portals)

**Comment by thecoolersevs** [comment]
Thank you so much. It works.
