### ISSUE TITLE
My MV portal don't work..... help me please 

### ISSUE THREAD

**Issue by Spirious111** [Multiverse/Multiverse-Portals#543]
Hello, i have a 1.12.2 minecraft server, and my Multiverse portal plugin don't want to work when i install him on the server, does anyone know why ?

Thanks

-Im not english so that's why i don't speak well english ! tell me if you didn't understood something. =)

**Comment by benwoo1110** [comment]
You need to use an older version:
for mv-core: https://dev.bukkit.org/projects/multiverse-core/files/2428161
for mv-portals: https://dev.bukkit.org/projects/multiverse-portals/files/2428333
