### ISSUE TITLE
how do I make my portal to run a command 

### ISSUE THREAD

**Issue by loumac321** [Multiverse/Multiverse-Portals#544]
so when players run through portal to go to a different world I want it to change their game mode from survival to creative and change it back to survival when they run back through please help

**Comment by UnFailed** [comment]
`/mvm set mode survival` - do this in survival world
`/mvm set mode creative` - do this in creative world

**Comment by benwoo1110** [comment]
Commands stated by UnFailed should be what you need. If you still have issues, you can create a new issue or ask in our discord  https://discord.gg/NZtfKky
