### ISSUE TITLE
Will not load...

### ISSUE THREAD

**Issue by G6Olivrrr** [Multiverse/Multiverse-Portals#546]
When starting up my server I constantly get this error. 
Could not load 'plugins\Multiverse-Portals-4.1.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: WOODEN_AXE 
i am using spigot 1.12

**Comment by benwoo1110** [comment]
For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

As for MV-portals, use this version: https://dev.bukkit.org/projects/multiverse-portals/files/898528

Learn how to create mv-portals with this guide: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Portals)

**Comment by G6Olivrrr** [comment]
That worked perfectly thank you!
