### ISSUE TITLE
Portals not working for non op players

### ISSUE THREAD

**Issue by UnFailed** [Multiverse/Multiverse-Portals#547]
I did `/lp group default permission set multiverse.portal.access*` but still nobody cant get trough them but only ops are allowed to go trough! It worked still in this morning for non op players but now it suddenly stopped working! ps sorry for bad English, but i ope you got the point!

**Comment by benwoo1110** [comment]
the permission node should be `multiverse.portal.access.*`. you may also need to give them `multiverse.access.WORLDNAME` for then actual access to the world first.

for more support relating to lp: https://discord.gg/luckperms

**Comment by UnFailed** [comment]
> the permission node should be `multiverse.portal.access.*`. you may also need to give them `multiverse.access.WORLDNAME` for then actual access to the world first.
> 
> for more support relating to lp: https://discord.gg/luckperms

I did all of those but it still didn't allow non op players to go trough portals!
But thank you for the help!

**Comment by benwoo1110** [comment]
Solved the issue via discord ;)
