### ISSUE TITLE
Why does my mv portal only work with ops 

### ISSUE THREAD

**Issue by loumac321** [Multiverse/Multiverse-Portals#548]
Please help my mv portals only work with ops how do I solve issue

**Comment by benwoo1110** [comment]
You need to use a permission plugin like luckperms to set permission for player to have access to using portals.

The permission node should be `multiverse.portal.access.PORTALNAME` .  You may also need to give them `multiverse.access.WORLDNAME` for them actual access to the world first.

To learn more about lp: https://discord.gg/luckperms

**Comment by CLiffbar0** [comment]
where do u put the multiverse.access.WORLDNAME

**Comment by benwoo1110** [comment]
you need to use a supported permission plugin like luckperms.

A startup guide by them: https://luckperms.net/wiki/Command-Usage

ask them if you face issues with luckperms:  https://discord.gg/luckperms

**Comment by meibeeart** [comment]
I am also having issues where only ops can use the portals! I have granted them both those permissions using Bpermissions mod but they can not use the portals still.

**Comment by benwoo1110** [comment]
For those having permission issue:
1. Have an up to date permission plugin like LuckPerms
2. see this page: https://github.com/Multiverse/Multiverse-Core/wiki/Permissions-(Portals)
3. If you don't know how to add permissions, its not an mv issue! Ask your permission plugin support.
