### ISSUE TITLE
Not showing up in plugins folder

### ISSUE THREAD

**Issue by iiIcy-yt** [Multiverse/Multiverse-Portals#552]
Multiverse is showing up in my plugins folder but Multiverse portals is not. I am running 1.12.2 and not getting any errors in console for some reason.

**Comment by benwoo1110** [comment]
ensure you are using this version of mv-portals: https://dev.bukkit.org/projects/multiverse-portals/files/2428333

**Comment by iiIcy-yt** [comment]
I am using the right version, I double-checked.

**Comment by benwoo1110** [comment]
Can you send your full server log via pastebin.com

**Comment by iiIcy-yt** [comment]
https://pastebin.com/A1rxDt0Y

**Comment by benwoo1110** [comment]
you need to install multiverse-core version 2.5 not 4.1.0: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by iiIcy-yt** [comment]
Ah. Alright thanks.
