### ISSUE TITLE
Lighting portals?

### ISSUE THREAD

**Issue by SCMPID007** [Multiverse/Multiverse-Portals#554]
I have multiverse core and multiverse portals installed on my server. When I make a new portal, it works perfectly. However, when I light the portal, it generates a nether portal in the destination world and spawns me in underneath it, suffocating me. Am I doing something wrong? I just want the portal to look like a portal...

**Comment by nicegamer7** [comment]
Can you provide the output of `/mvv -b --include-plugin-list`?

**Comment by SCMPID007** [comment]
https://pastebin.com/J2JPbqWs

**Comment by nicegamer7** [comment]
Could you please try the latest CI versions of the MV plugins?

Available here: https://ci.onarandombox.com/view/Multiverse/

Just click on the plugin's name and download the file from under `Last Successful Artifacts`.

**Comment by benwoo1110** [comment]
should be fixed by #570

**Comment by nicegamer7** [comment]
Looks to be a similar issue to #588, try the test build of #584 and let us know if that fixes the issue.

**Comment by nicegamer7** [comment]
Should be fixed by #584.
