### ISSUE TITLE
Does Not Work In 1.8.8

### ISSUE THREAD

**Issue by YawnTM5** [Multiverse/Multiverse-Portals#557]
So, I tried putting this plugin along side Multiverse Core 4.1!
It does not create a folder and it doesn't show up in /plugins either.. I know it should only work in 1.12 and Above but i do have Via Version that makes plugins Backwards Compatible + It should be able to work with 1.8.8 anyways! Considering you have made 1.8.1 (that nobody uses) Why not add the feature of 1.8.8? I tried the 1.8.1 plugin btw.. Did not work!

**Comment by benwoo1110** [comment]
Multiverse Core 4.1 only works 1.13 and up. You will need to use an even older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527. for mv-portals https://dev.bukkit.org/projects/multiverse-portals/files/771760
