### ISSUE TITLE
Portal doesnt work suddenly?

### ISSUE THREAD

**Issue by zekromblitzi** [Multiverse/Multiverse-Portals#560]
So I've used portals to teleport to multiverse worlds, but one portal isnt working. the destination doesnt link and /mvpmodify dest (output portal) -p (portal). It just says it doesnt exist.

**Comment by benwoo1110** [comment]
high chance you are just running to command wrongly https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference-(Portals)#modify

Not much info is provided so I will be closing this issue. If you still face issues, create a new issue and follow the issue template, thanks!
