### ISSUE TITLE
Destroyed bed. Stuck in the end loop. World spawn ignored.

### ISSUE THREAD

**Issue by amcmanu3** [Multiverse/Multiverse-Portals#564]
Very specific case that my players find themselves in. People get stuck in the end when they destroy their bed in the main world then go to the end. The return end portal does not bring them back to the world spawn of the main world it puts them on top of the block stack at the return portal. 
I proved this by uninstalling all MV plugins and I make it through the portal when I have no bed, however, when multiverse is installed I get stuck in a constant loop. If you need logs please let me know.
[2020-08-24 17-09-52.zip](https://github.com/Multiverse/Multiverse-Portals/files/5120263/2020-08-24.17-09-52.zip)

**Comment by benwoo1110** [comment]
Should be related to https://github.com/Multiverse/Multiverse-Core/issues/2160

**Comment by benwoo1110** [comment]
Closing this as its a duplicate, and issue is with mv-netherportals not mv-portals.
