### ISSUE TITLE
selecting in world edit doesn't work

### ISSUE THREAD

**Issue by EXPNODE** [Multiverse/Multiverse-Portals#567]
### Information

* **Server version:** <https://imgur.com/d5dqkfi-->

* **Full output of `/mv version -b`:** https://pastebin.com/JKG2HHgT

* **Server log:** https://gist.github.com/EXPNODE/cd24971b5cfa88f5cae6a2ded6342155

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
World edit select doesn't work https://dev.bukkit.org/projects/worldedit/files/3039216

**Steps to reproduce**  
select something with world edit and try to create a portal

**Expected behavior**  
i wanted it to create a portal

**Screenshots**  
https://imgur.com/lm0UwE3

**Comment by benwoo1110** [comment]
Issue solved in discord!
