### ISSUE TITLE
My Members Can’t Use Portals

### ISSUE THREAD

**Issue by jackgraddon** [Multiverse/Multiverse-Portals#572]
I installed this, core, and inventories to separate a hub world and a survival smp world. It works great, other than the fact I have to manually tp anyone who wants to go through the portals I have set up. In PermissionsEX, I have the “multiverse.portal.access.(portal names)” for all portals, yet they still cannot. My mods, who inherit all permissions from default, can. So can I of course, but I am OP. Not sure what is causing this issue.

**Comment by benwoo1110** [comment]
firstly, permissionEx is outdated and unsupported. Please use LuckPerms. `multiverse.portal.access.(PORTALNAME)` is to correct permission node, but take note that if you enabled enforceaccess in mv-core you will also need to give `multiverse.access.WORLDNAME` permission node.

**Comment by jackgraddon** [comment]
Does multiverse.access.* work for all worlds? And the same with the portal permission? That is what I have. Also, just swapped over to LuckPerms.

**Comment by jackgraddon** [comment]
Not relevant anymore, reset my server and it seems to work.
