### ISSUE TITLE
Nether Style Portal Teleports without Perms

### ISSUE THREAD

**Issue by nicegamer7** [Multiverse/Multiverse-Portals#580]
### Information

* **Server version:**
Paper Build 216.

* **Full output of `/mv version -p`:**
https://j.mp/3nuSc9t

* **Server log:**
https://paste.gg/p/anonymous/645c7308b9684aa6a87f07027b4ad64a

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
If you enter a Multiverse-Portal filled with the `nether_portal` block, and you don't have permission to use it, you'll be teleported to the nether. This shouldn't happen, even with `portalsdefaulttonether` enabled.

**Steps to reproduce**  
1. OP yourself and create a portal filled with the `nether_portal` block.
2. DeOP youself and stand in the portal.

**Expected behavior**  
You shouldn't go anywhere.

**Comment by nicegamer7** [comment]
Possibly fixed by #584. I need to test it though.

**Comment by benwoo1110** [comment]
this should be fixed as well?

**Comment by nicegamer7** [comment]
You fixed this with #625 right?

**Comment by benwoo1110** [comment]
yea, good to test on the latest CI build to see if it works.

**Comment by nicegamer7** [comment]
Alright, I'll test it right now.
