### ISSUE TITLE
Portal generating where I do not want it to

### ISSUE THREAD

**Issue by FishbirdDD** [Multiverse/Multiverse-Portals#588]
### Information

* **Server version:** Paper 253 (MC 1.16.3) API version 1.16.3-R0.1-SNAPSHOT

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/16efd27bda38472284103b910a806610

* **Server log:** 
[latest(1).log](https://github.com/Multiverse/Multiverse-Portals/files/5478840/latest.1.log)

### Help request

**Problem**
When I use a portal to teleport to coordinates in another world, it spawns a portal where I spawn in. I think this could be related to the fact that when the portals are not linked to MV-P, it takes me to the nether of a different world. The word that the portal is in is LobbyPhoenix37 and the world I am teleporting to is PlotsWorld. The nether that it brought me to is mainworld_nether. There is not a world titled LobbyPhoenix37_nether nor one called PlotsWorld_nether

**What I have tried**
I've not tried much other than downloading Multiverse-NetherPortals hoping it would somehow fix the issue. I've done a setup like this multiple times before and not had any issues. I feel like there's something I'm missing here.

Note: This only happens in creative mode. Perhaps could be related to the fact that PlotsWorld's default gamemode is creative?

**Comment by benwoo1110** [comment]
It sounds like you want all (nether?) portals generated on a world to go to another overworld instead of the nether world? You explanation is rather confusing.

**Comment by FishbirdDD** [comment]
Sorry if it was confusing
This is the important part:
> When I use a portal to teleport to coordinates in another world, it spawns a portal where I spawn in.
If I go through the portal that is taking me to the coordinates in PlotsWorld, it creates a portal there (if I am in creative mode going through it). I can upload a video if needed

**Comment by benwoo1110** [comment]
Yea i think a video will be good.

**Comment by FishbirdDD** [comment]
https://drive.google.com/file/d/1LwXTQHgTgr8Ca59DvX1dsruAapePLvn0/view?usp=sharing

Here is a google drive link to the video. It hasn't processed yet so sorry if you can't view it right away.

**Comment by nicegamer7** [comment]
This might be fixed by #584, I'll post a test build there when I get the chance.

**Comment by nicegamer7** [comment]
I've just posted a test build of #584 and I'm fairly confident it fixes this issue. Give it a shot and let us know.
