### ISSUE TITLE
Plugin wont install

### ISSUE THREAD

**Issue by TheNiceGaamer** [Multiverse/Multiverse-Portals#597]
Information
Server version: spigot version: 1.12.2

Problem
When i drag and drop the "Multiverse-Portals-4.2.1.jar" into my "plugins" folder it doesn't install the folder and doesn't appear in "/plugins" yes i have the "Multiverse-Core-4.2.2.jar" plugin installed 

What I have tried
installing other versions of multiverse portals

**Comment by benwoo1110** [comment]
MC 1.12 You will need to use an older version of Multiverse Core - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161

AS for mv-portals, this version should work: https://dev.bukkit.org/projects/multiverse-portals/files/2428333

**Comment by nicegamer7** [comment]
I'm going to close this due to inactivity. If you still need help, open a new issue or join us on Discord!
