### ISSUE TITLE
Won't load on 1.8.8 -- java.lang.NoSuchFieldError: WOODEN_AXE

### ISSUE THREAD

**Issue by SeerLite** [Multiverse/Multiverse-Portals#612]
### Information

* **Server version:** 
`This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
Spigot 1.8.8 gotten from BuildTools.

* **Full output of `/mv version -p`:** 
https://j.mp/3sQSTMP

* **Server log:** 
https://gist.github.com/SeerLite/a72fd5567323978c4edb61685dd1d7b9

### Details
I was **able** to reproduce my issue on a freshly setup and up-to-date(? 1.8.8) server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Multiverse-Portals won't load on 1.8.8 (AFAIK this version is supported, let me know if I'm wrong). I tried with both 4.2.1 from bukkit.org and 4.2.2 snapshot from Jenkins. Log above is from using 4.2.2.

**Steps to reproduce**  
Put the Multiverse-Portals jar file in the plugins directory and start the server. The plugin won't be loaded.

**Expected behavior**  
The plugin would load.

Thank you for the amazing work on these plugin!

**Comment by benwoo1110** [comment]
1.8.8 isnt supported by latest version of mv.

MC 1.8.x You will need to use an even older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527

As for portals, you can try this build https://dev.bukkit.org/projects/multiverse-portals/files/898528

**Comment by SeerLite** [comment]
Just now saw that this only supports 1.13 and forward. Sorry for the spam and thank you so much for the help!
