### ISSUE TITLE
Wrong view portal position

### ISSUE THREAD

**Issue by WareZ57** [Multiverse/Multiverse-Portals#613]
Hello,

When we take a portal, it positions the camera in the wrong direction, how to remedy that?

Short vid: https://streamable.com/fxha8r

/mv version https://j.mp/2Nr9mrf

Server running on : Mohist 1.16.5-367 (Forge 36.0.42 & API  Version 1.16.5-R0.1-SNAPSHOT)

Thanks you

**Comment by benwoo1110** [comment]
You should set direction for your portal destination, so instead of `p:spawn`, do something like `p:spawn:n`. Full list of direction can be found at: https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#portal-destinations---requires-multiverse-portals
