### ISSUE TITLE
Portal for survival question 

### ISSUE THREAD

**Issue by collin12345432** [Multiverse/Multiverse-Portals#614]
Hi i have a minecraft server with survival and multiverse portals plugin and i want a otter plug-in that tps players to the location Theo left of but het also need to be tpted back to the nether of end of Theun were there.

**Comment by nicegamer7** [comment]
I believe the `last_location` share in Multiverse-Inventories should do what you want.

**Comment by collin12345432** [comment]
Does the last location also work if you go into the nether and log off and come back on and spaan in the lobby and go in the mv portal to go to survival Will you be in the nether or in the overwold at the portal because i want them to be in the nether if they log off there

**Comment by nicegamer7** [comment]
If you group your survival worlds, they will spawn in the nether.
