### ISSUE TITLE
Portals teleporting in to void

### ISSUE THREAD

**Issue by SirCraftypants** [Multiverse/Multiverse-Portals#615]
I'm on Paper Spigot 1.16.5
MC Client 1.16.5
Premium Server

i was on Portals 4.2.0 for last 4 months, also on Core 4.1.0, all my Portals were working perfectly fine.

Today I updated Portals to 4.2.1 and all my portals are now malfunctioning.

Two things are happening

1. When i exit a certain portal and i try to walk, i'm pulled back to the exit spot for around 4 seconds.
2. When i enter a certain portal i'm transported in the right direction but no where near the exit portal and in the wrong location, then after about 5 seconds im transported again but this time to the correct location.

I then attempted to update both Core and Portals to the latest as of today and nothing changed.

I have no idea how or why this has happened, as described above it just started happening out of the blue without any updates and all i did was create two new portals. The affected portals are the two new portals and the previously two created portals which we initially working perfectly, the only portals that are working perfectly still are my lobby portals.

The only commonality the affected portals have are, that that are positioned 18 blocks up from the lowest build point in MC.

**Comment by nicegamer7** [comment]
Please fill out the issue template fully (including uploading the files it tells you to), as we can't help without that information.

**Comment by SirCraftypants** [comment]
The only thing i've not provided is the server log or screenshots, i have no screenshots and even if i did they would not tell you anything.

I did not provide a server log because nothing appears in my Console so you will find nothing in it. 

So no Errors or Warns, the only things i did were stated above, all the version information is above.

The only other thing i did was create a new worldguard region but that region is setup in exactly the same way my other regions are set, i've triple checked everything. all my other portals are working fine, it's just the last 4 portals, i've even removed them and recreated them and they still fail. portal 1 to 2 works fine, portal 2 to 1 fails, you're teleported about around 10 to 15 blocks away from the portal, then 5 seconds later teleported again only this time to the portal.

**Comment by SirCraftypants** [comment]
> 
> 
> Please fill out the issue template fully (including uploading the files it tells you to), as we can't help without that information.

The only thing i've not provided is the server log or screenshots, i have no screenshots and even if i did they would not tell you anything.

I did not provide a server log because nothing appears in my Console so you will find nothing in it.

So no Errors or Warns, the only things i did were stated above, all the version information is above.

The only other thing i did was create a new worldguard region but that region is setup in exactly the same way my other regions are set, i've triple checked everything. all my other portals are working fine, it's just the last 4 portals, i've even removed them and recreated them and they still fail. portal 1 to 2 works fine, portal 2 to 1 fails, you're teleported about around 10 to 15 blocks away from the portal, then 5 seconds later teleported again only this time to the portal.

The issue is that portals 2 to 1 are teleporting you as they should, fail to teleport you where they should, then it's like it's correcting it's mistake by re-teleporting you to the right location.  That's all i can tell you.

**Comment by nicegamer7** [comment]
While I don't doubt there is nothing in the server log, I would still prefer you posted it, just so we can be sure. Additionally, you missed the output link of `/mvv -p`.

**Comment by SirCraftypants** [comment]
Latest Log, i'd restarted the server after updating both mvp and mv, then tested the portals and it was still doing the above, as you can see nothing in the log. I can provide the previous log to that but again, you'll find nothing it it.
https://paste.helpch.at/oqukisoyut.md


Admittedly i did miss the mvv -p
https://paste.helpch.at/upeqazoneg.cs

**Comment by SirCraftypants** [comment]
I updated to 4.2.2 Core but the teleport issue still persists, I know it's a strange one as it just started happening out of the blue after i created two new portals. Not only did the new portal from 2 to 1 fail, but the previously set 2 to 1 portal started failing also.

I've tried removing them and re creating them but that doesn't work, i've tried rolling them back to the previous versions but again no change. 

I've noticed that you only have both plugins marked as 1.16.3 and i'm using them on 1.16.5 but there were working fine on 1.16.5 for the last month up until i created this new portal yesterday.  

I've given all the information i have available now. If there's nothing you can think of to solve this or nothing you can do then i'll have no choice but to find another plugin.

**Comment by benwoo1110** [comment]
@SirCraftypants are the portals filled with anything, e.g. purple nether effect or water?

**Comment by nicegamer7** [comment]
I have the same question as ben. I'd also like to know if this build changes anything, https://github.com/Multiverse/Multiverse-Portals/pull/584#issuecomment-744162347 (try with empty portals and ones filled with nether portal block).

Another thing I noticed from your startup log is that you have lots of plugins, it could also be worth trying your portals without those plugins installed, so that we can see if it caused by a plugin conflict.

**Comment by SirCraftypants** [comment]
I'm using Air for my portals, first using glass then removing the glass once set.  I'm in the process of removing plugins to see if another plugin is causing it, all the plugins i updated just before it started happening but no luck so far.

**Comment by SirCraftypants** [comment]
I've also added teleport: allow to all regions and now removed every other plugin one by one and it's still not teleporting to the portal, it's first teleporting about 15 blocks away, then teleporting again but to the server like it's correcting it's mistake, occasionally preventing me from proving too soon upon arrival. So all of my other plugins are eliminated, to make absolutely sure i restarted my server one last time.

**Comment by SirCraftypants** [comment]
I just realized another difference to the portals that are working and those that are not, those that are not working properly are in the same world as each other..

**Comment by benwoo1110** [comment]
I cant reproduce this errors, since you mentioned void world, it's possible its safety teleporter doing its thing. You can try set in portals.yml `safeteleport` to false for those affected portals.

**Comment by SirCraftypants** [comment]
> 
> 
> I cant reproduce this errors, since you mentioned void world, it's possible its safety teleporter doing its thing. You can try set in portals.yml `safeteleport` to false for those affected portals. Note, best to do config changes with your server is off.

i/ll try this, and get back to you either way, ty

**Comment by nicegamer7** [comment]
I also noticed from your startup log that you're using MV Portals version 4.2.0.

So just to clarify, this issue came up on 4.2.1 and is now affecting 4.2.0?

**Comment by SirCraftypants** [comment]
I will attempt to explain it clearer.

I was on:

Multiverse Core 4.1.0 & Multiverse Portals 4.1.0 on my 1.16.5 Paper Spigot Server

Everything was working fine with all my Portals since i started out on 1.15.2 Paper Spigot.

Then yesterday I created 2 new portals and then it all started to go wrong. The last 2 portals i created that were working fine and these two new portals all started to malfunction. While the first two portal linking my lobby world to this world with the four malfunctioning portals is still working perfectly.

The difference between the four malfunctioning portals and the two portals working fine are as follows.

The two working portals linked together are linking one world to another world and the portals are no where near void as they're both in the center of two huge 400x400 blocks sky islands.

The 4 malfunctioning portals are close to the edge of one of those sky islands.

So next i updated to the latest 1.1 versions of Core and Portals, tried them all and it did not fix the problem.

OK so i turned safe teleport to false as instructed on the affected portals and restarted and it's done nothing, the problem still persists.

**Comment by nicegamer7** [comment]
So the problem even occurred on version 4.1.0?

**Comment by SirCraftypants** [comment]
> 
> 
> So the problem even occurred on version 4.1.0?

It started on 4.1.0 after creating two new portals correct, then i updated and it failed to fix the issue.

**Comment by SirCraftypants** [comment]
> 
> 
> > So the problem even occurred on version 4.1.0?
> 
> It started on 4.1.0 after creating two new portals correct, then i updated and it failed to fix the issue.
> 
> But the strange part is, the first two portals i created linking 1 world to another still works fine. It's only the 4 portals in the same world near void that are not working right.

Would you like to see it for yourself?

**Comment by nicegamer7** [comment]
A short video would work, although, I don't think it's necessary as I understand the problem as described.

Could you run `mv debug 3` from the console then try one of these portals, and send us the output.

**Comment by SirCraftypants** [comment]
> 
> 
> A short video would work, although, I don't think it's necessary as I understand the problem as described.
> 
> Could you run `mv debug 3` from the console then try one of these portals, and send us the output.

https://paste.helpch.at/qukebewoho.cs

**Comment by SirCraftypants** [comment]
> 
> 
> > A short video would work, although, I don't think it's necessary as I understand the problem as described.
> > Could you run `mv debug 3` from the console then try one of these portals, and send us the output.
> 
> https://paste.helpch.at/qukebewoho.cs

that's in one and out the other with the error occurring.

**Comment by SirCraftypants** [comment]
I've finally eliminated Spartan Anticheat and WorldGuard from the cuplrit list, all the other plugins i use were removed one by one and the issue persisted.

**Comment by nicegamer7** [comment]
Okay, I suppose a short video wouldn't hurt.

I tried to replicate this on my end but couldn't

**Comment by SirCraftypants** [comment]
> 
> 
> Okay, I suppose a short video wouldn't hurt.
> 
> I tried to replicate this on my end but couldn't.


Video file is to big for here so i've shared it in my dropbox https://www.dropbox.com/s/9p3ets5hzqqsohp/bandicam%202021-02-26%2017-10-20-614.mp4?dl=1

**Comment by SirCraftypants** [comment]
I'm going to try completely removing all my portals, remove the plugin entirely and start again with latest, if you're still unable to solve it.

**Comment by nicegamer7** [comment]
I watched the video yesterday and I'm not sure what would cause that. Since you don't have too many portals it shouldn't be too much work to set them up again. Let us know if that fixes it.

**Comment by SirCraftypants** [comment]
> 
> 
> I watched the video yesterday and I'm not sure what would cause that. Since you don't have too many portals it shouldn't be too much work to set them up again. Let us know if that fixes it.

OK, i did a complete fresh install and portals setup and the bug is still occurring.

**Comment by SirCraftypants** [comment]
### **SOLUTION/FIX**

I've found out why it was happening, it was because chunks where the portals were were not loading fast enough so you fall through the floor. 

The issue here is , this happens with you create large sky islands and place the portals closer to the edge of the island, server lag can also cause this so, the solution is to use a keep chunks loaded plugin like Keepchunks to permanently keep selected chunks around a portal loaded whether or not a player is there or not.  Though i'd leave this here and update the title to help future help others with same issue.

**Comment by nicegamer7** [comment]
Glad to hear you figured it out. We'll keep this in mind next time someone reports something similar. Thanks for letting us know 😀!

**Comment by benwoo1110** [comment]
Maybe paper async teleport and chunk loading may help
