### ISSUE TITLE
Minecraft multiverse-portals/lastlocation plugins random portal no safe location plugin need help

### ISSUE THREAD

**Issue by OriginXOfficial** [Multiverse/Multiverse-Portals#617]
I am trying to make a portal (with multiverse-portals plugin) from the spawn world to the default world (named 'world'). I make the portal with the command /mvpcreate portal1 then i do /mvpmodify dest w:world. And to make it randomized i do /ll cfg rtp portal1 10 29999956 10 29999956 (with the lastlocation plugin). But whe i want to go through it gives me a message 'No safe locations found!'. When i made a randomized portal to another world called 'publicworld' it worked but now when i want to change it it doesn't work. Could anyone please help me? Let me know if you need any extra information.

**Comment by benwoo1110** [comment]
try set `safeteleport` to false in portals.yml. Or you can just use a safer spawn location by using `/mvsetspawn` to set a new spawn location

**Comment by OriginXOfficial** [comment]
> try set `safeteleport` to false in portals.yml. Or you can just use a safer spawn location by using `/mvsetspawn` to set a new spawn location

Thanks it worked!

**Comment by OriginXOfficial** [comment]
> > try set `safeteleport` to false in portals.yml. Or you can just use a safer spawn location by using `/mvsetspawn` to set a new spawn location
> 
> Thanks it worked!

And i mean that /mvsetspawn worked.
