### ISSUE TITLE
Multiverse Portals suddenly don't work [BUG!]

### ISSUE THREAD

**Issue by WolfyRed** [Multiverse/Multiverse-Portals#618]
### Information

* **Server version:** git-Spigot-dcd1643-e60fc34 `(MC: 1.12.2)`

* **Full output of `/mv version -p`:** 2.7.0-SNAPSHOT-b751 
 https://paste.gg/p/anonymous/4ee665ae45bd4ffbac3533718aec7130

* **Server log:**
 https://gist.github.com/WolfyRed/02f8e3514da23828b6dbed3fa9f74549

* **Main focus:** 
 https://paste.gg/p/anonymous/6885bf6c741f4753b7985f087b899729

### Details
I was **`not able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Walking into a portal does nothing.

**Steps to reproduce**  
1. Make a Multiverse portal
2. Go inside of the portal
3. You don't get teleported anywhere, nothing happens
4. When that "nothing" happens, somewhere, a giant bug has entered the console, causing it to spam errors continuously within a span of milliseconds  *(Until you step out of the area of the portal)*

**Expected behavior**  
To go into the portal, and to be teleported to a different world, as was the behavior last week.  *(Still the same `Multiverse-Core` and `Multiverse-Portals` version.)*

**Media**  

A video of me (The {User}) walking into a yellow portal

https://user-images.githubusercontent.com/66114400/111903380-6b5c6e80-8a18-11eb-9df3-34febaba051d.mov

**Comment by benwoo1110** [comment]
You probably have the wrong version of mvcore, 1.12 is unsupported as well.

MC 1.12 You will need to use an older version of Multiverse - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by WolfyRed** [comment]
> You probably have the wrong version of mvcore (or portals), 1.12 is unsupported as well.
> 
> MC 1.12 You will need to use an older version of Multiverse - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161

It may be unsupported but there are many players that use 1.8, for combat reasons
