### ISSUE TITLE
Could not pass event PlayerBucketFillEvent

### ISSUE THREAD

**Issue by ErythroCraft** [Multiverse/Multiverse-Portals#619]
### Information

* **Server version:** https://gist.github.com/ErythroCraft/a58246974debcac80520462d1cd48441

* **Full output of `/mv version -p`:** https://gist.github.com/ErythroCraft/9e0d09f8dc7cb3d3d491bbaa9c3bd7f7

* **Server log:** https://gist.github.com/ErythroCraft/c2afc3676fdad3a68fa7940525bb6ca2

### Details
I was **`<not able>`**

**Description**  
So, if I or player fill lava in buckets, the server console give out an error.
Could not pass event PlayerBucketFillEvent to Multiverse-Portals v4.2.0-b826 ....
Show full log or this. https://gist.github.com/ErythroCraft/fe511295d7d50d4df1570f255c727e53

**Steps to reproduce**  
Steps are simple. Right click with bukkit on lava to fill the bucket with lava.

**Expected behavior**  
not more

**Screenshots**  
no screenshots

**Comment by nicegamer7** [comment]
This was fixed in version 4.2.1, you just need to update.
