### ISSUE TITLE
Set world destination to a player's previous location instead of spawn

### ISSUE THREAD

**Issue by ggtylerr** [Multiverse/Multiverse-Portals#628]
### Feature request

**Feature description**
*Sorry if this is already a feature or if this is the wrong repo to make this request. I'm not well versed in plugins.*

Instead of having the world destination sending users to the spawn, have it (or a separate type of destination) teleport them to their previous location in that world or world group. 

To clarify, it'd be a similar functionality to portals in hubs that's seen in many different servers. So, let's say a player logs off in a survival world at their house. When they come back on to the server hub, instead of sending them to the spawn of a world, it'll send them back to their house. This would also work for linked worlds, so if they leave in the nether or the end, it'll also send them there.

**How the feature is useful**
As mentioned, there are plenty of servers that have hubs. This feature would provide the same functionality as that. *(AFAIK, there's somehow no free plugins that have this. Don't quote me on that though.)*

**Comment by pseudoforceyt** [comment]
Install Multiverse Inventories (if you havent) and run  `/mvinv toggle last_location` :)

**Comment by benwoo1110** [comment]
As stated, look int my-inv’s last location feature.

**Comment by ggtylerr** [comment]
Looks like that does work, but the command seems to apply to *every* world change, including warps and spawns from Essentials. Should I make a bug on the mv-inv repo?

**Comment by benwoo1110** [comment]
It’s just how it works for now. Suggestions has been made to make them per world, it will be implemented when we deem possible.
