### ISSUE TITLE
No return from the end

### ISSUE THREAD

**Issue by XDNikoko** [Multiverse/Multiverse-Portals#634]
So, I can use the end portal in the overworld just fine, but when I go through the end portal in the end, to return to the overworld, it says in chat "You have no home bed or charged respawn anchor, or it was obstructed". Meaning that I don't have a set spawnpoint, even though I set a worldspawnpoint, I used a bed, I used /spawnpoint. I've tried everything, but nothing works. I've tried to find anyone else with the same problem, but I can't find anything. Please help

### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
How is this related to mv-portals? Anyways, you probably want to do something like `/mvm set respawnWorld <overworld> <endworld>`

**Comment by zhgt** [comment]
The same thing is happening to me, I am not finding a solution. The problem is with end portals in an end world.
