### ISSUE TITLE
I can't start my Aternos Server

### ISSUE THREAD

**Issue by Atten007** [Multiverse/Multiverse-Portals#639]
Hi folks,

I have a free Minecraft Server that does run on https://aternos.org with this plugin (Multiverse-Portals). But when I'm starting my Aternos Minecraft Server, it does load and then it crashes because Multiverse-Portals takes too long to start. Multiverse-Portals lets crash my Aternos Minecraft Server. Is there a problem in this plugin? If it's a error can you then please fix this very shitty error?

Sincerely yours,
Atten007😊

**Comment by benwoo1110** [comment]
Sounds like an aternos issue then. Bukkit servers don't have timeouts for plugin loading. Anyways issue template is there for a reason, so please fill it up.

**Comment by benwoo1110** [comment]
Closing as no follow up from issue author.
