### ISSUE TITLE
"last_location" issue

### ISSUE THREAD

**Issue by vitorgueler22** [Multiverse/Multiverse-Portals#641]
Hey, so, I will try to explain this the best as I can. I've enabled /mvinv toggle last_location, and I want to create two portals and give players two options: one portal leads to the last location, and the other to the hub, both on the survival world. On the last location I've put /mvp create (name) world, it spawned on the last location, fine. On the hub server, I specified an anchor as the destination, and it still spawned in the last location. Is it possible to have both options and force a spawn in the hub on the hub portal?

**Comment by benwoo1110** [comment]
This issues is more for mvinv than mvp, we already know of this limitation, we will work on improving mvinv if time allows, but no promises.
