### ISSUE TITLE
WorldEdit v7.2.9+e20e013 is incompatible with Multiverse-Portals v4.2.1-b834

### ISSUE THREAD

**Issue by tinu1976ch** [Multiverse/Multiverse-Portals#642]
### Information

* **Server version:** Paper version git-Paper-439 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-Snapshot)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/8794da0a09ee4ec697225f653b50916d

* **Server log:** [Multiverse-Portals] WorldEdit v7.2.9+e20e013 is incompatible with Multiverse-Portals v4.2.1-b834

### Details
I was **`<able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
just wanted to activate WorldEdit with PlugManX

**Steps to reproduce**  
start server with the following files : 
- Multiverse-Core-4.3.1.jar
- Multiverse-Portals-4.2.1.jar
- Multiverse-SignPortals-4.2.0.jar
- PlugManX.v2.2.9.jar
copy worldedit-bukkit-7.2.9.jar to server
activate WorldEdit via PlugManX

**Expected behavior**  
no error message in console

**Screenshots**  
no screenshot necessary. for error message look above *server log*

**Comment by nicegamer7** [comment]
This is almost certainly caused by PlugMan.

**Comment by benwoo1110** [comment]
Also do full restarts when adding / removing plugins.
