### ISSUE TITLE
Portals not returning.

### ISSUE THREAD

**Issue by jacklollz2** [Multiverse/Multiverse-Portals#647]
Player spawns in World1, the default.
Player enters World2.
Player creates a nether portal in World2.
Player goes through the portal, enters nether.
Player comes back through the portal, located in the nether.
Player enters World1, instead of the original portal in World2.

What can I do to resolve this?

**Comment by NeverGrowUp** [comment]
Use mv-netherportals plugin rather than mv-portals plugin.

**Comment by jacklollz2** [comment]
> Use mv-netherportals plugin rather than mv-portals plugin.

Thank you
