### ISSUE TITLE
How to dispaly particle effects in multiverse portal

### ISSUE THREAD

**Issue by Prsna2988** [Multiverse/Multiverse-Portals#653]
The players in my server cant seem to locate or mistakenly enter the portal please help me to solve this problem also one user said type [ /mvpm fill ] command would work but it didn't please help.

**Comment by zax71** [comment]
You can place water or lava in a portal to make it show like below
![image](https://github.com/Multiverse/Multiverse-Portals/assets/67716263/ae962cf2-9fda-4b24-a54b-67ae67c1883f)

**Comment by Prsna2988** [comment]
Wont the water/lava flow out?

**Comment by zax71** [comment]
https://tryitands.ee nope

**Comment by Prsna2988** [comment]
Does it work with custom liquids?

**Comment by NeverGrowUp** [comment]
So now I'm guessing you are using a modded server. We don't support modded servers. Only spigot/paper etc.
So as Zax said.... Try it and see.

**Comment by zax71** [comment]
Modded servers are not supported
