### ISSUE TITLE
Portals not working in 1.20 or 1.20.1

### ISSUE THREAD

**Issue by CollaboK8** [Multiverse/Multiverse-Portals#655]
### Information

* **Server version:** 
* 1.20.1

* **Full output of `/mv version -p`:**  https://gist.github.com/CollaboK8/77068d50e48f0507191db666823f99be 

* **Server log:**  
* https://gist.github.com/CollaboK8/1dab7027811ba01c4b093e488003168f 

### Details
I was **`able `** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

Portals will not work on 1.20 or 1.20.1 but will work if you use a portal in a 1.19.4 world - i.e it will take you to the 1.20 world but the 1.20 portal then cant take you to the 1.19.4 world or a new 1.20 world 

**Steps to reproduce**  

Generate a new 1.20.1 world 
Upload a 1.19.4 world
Create a portal in both worlds and link the portals. You will be able to travel from 1.19.4 to 1.20.1 but not 1.20.1 to 1.19.4
Removal all portals
Create a new 1.20.1 world with MV
Create portals in both 1.20.1 worlds
You will not be able to travel between the two 1.20.1 worlds 

**Expected behavior**  

You will be able to use the portal between 1.19.4 to 1.20.1 but will not be able to go form 1.20.1 world to 1.19.4 world
You will not be able to use portals in 1.20.1 worlds to travel to each other.
**Screenshots**

**Comment by CollaboK8** [comment]
fresh 1.20.1 server with nothing but paper, MV core and MVP still gives the same result of not being able to use portals in 1.20.1. Did a server restart after testing to show full start-up as log wasn't showing in full

22.06 12:21:33 [Server] WARN [Multiverse-Core] Original Location: X: 0 Y: 66 Z: 0 P: 0 Y: 0 
22.06 12:21:33 [Server] ERROR [Multiverse-Core] Safe spawn NOT found!!!
22.06 12:21:33 [Server] INFO [Multiverse-Core] Loading World & Settings - 'testing_the_end' - Env: THE_END - Type: NORMAL & seed: 3319417116188280587
22.06 12:21:33 [Server] INFO [Multiverse-Core] 3 - World(s) loaded.
22.06 12:21:33 [Server] WARN [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
22.06 12:21:33 [Server] INFO [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
22.06 12:21:33 [Server] INFO [Multiverse-Portals] Enabling Multiverse-Portals v4.2.1-b834
22.06 12:21:33 [Server] INFO [Multiverse-Portals] 0 - Portals(s) loaded
22.06 12:21:33 [Server] INFO [Multiverse-Portals 4.2.1-b834]  Enabled - By Rigby and fernferret
22.06 12:21:33 [Server] INFO Running delayed init tasks
22.06 12:21:33 [Server] Startup Done (3.724s)! For help, type "help"
22.06 12:21:33 [Server] INFO Timings Reset
22.06 12:22:27 [Server] INFO CollaboK8 joined the game
22.06 12:22:27 [Multicraft] CollaboK8 ran command Message of the Day
22.06 12:22:54 [Disconnect] User CollaboK8 has disconnected, reason: Disconnected
22.06 12:22:54 [Server] INFO CollaboK8 left the game
22.06 12:23:25 [Server] INFO Made CollaboK8 a server operator
22.06 12:23:25 [Multicraft] CollaboK8 ran command: op CollaboK8
22.06 12:23:51 [Multicraft] Updating config server.properties: True, Config file updated.
22.06 12:24:49 [Multicraft] Updating config server.properties: True, Config file updated.
22.06 12:25:23 [Multicraft] Received restart command
22.06 12:25:23 [Multicraft] Stopping server!
22.06 12:25:23 [Server] INFO Saving the game (this may take a moment!)
22.06 12:25:24 [Server] INFO Saved the game
22.06 12:25:24 [Server] INFO Stopping the server
22.06 12:25:24 [Server] INFO Stopping server
22.06 12:25:24 [Server] INFO [Multiverse-Portals] Disabling Multiverse-Portals v4.2.1-b834
22.06 12:25:24 [Server] INFO [Multiverse-Core] Disabling Multiverse-Core v4.3.1-b861
22.06 12:25:24 [Server] INFO Saving players
22.06 12:25:24 [Server] INFO Saving worlds
22.06 12:25:24 [Server] INFO Saving chunks for level 'ServerLevel[testing]'/minecraft:overworld
22.06 12:25:24 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing'
22.06 12:25:24 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing'
22.06 12:25:24 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Saved 1584 block chunks, 92 entity chunks, 0 poi chunks in world 'testing' in 0.76s
22.06 12:25:25 [Server] INFO ThreadedAnvilChunkStorage (testing): All chunks are saved
22.06 12:25:25 [Server] INFO Saving chunks for level 'ServerLevel[testing_nether]'/minecraft:the_nether
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing_nether'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing_nether'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing_nether'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Saved 0 block chunks, 26 entity chunks, 0 poi chunks in world 'testing_nether' in 0.00s
22.06 12:25:25 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
22.06 12:25:25 [Server] INFO Saving chunks for level 'ServerLevel[testing_the_end]'/minecraft:the_end
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing_the_end'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing_the_end'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing_the_end'
22.06 12:25:25 [Server] INFO [ChunkHolderManager] Saved 0 block chunks, 10 entity chunks, 0 poi chunks in world 'testing_the_end' in 0.00s
22.06 12:25:25 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
22.06 12:25:25 [Server] INFO ThreadedAnvilChunkStorage: All dimensions are saved
22.06 12:25:25 [Server] INFO Flushing Chunk IO
22.06 12:25:25 [Server] INFO Closing Thread Pool
22.06 12:25:25 [Server] INFO 2023-06-22 12:25:25,475 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
22.06 12:25:25 [Server] INFO Closing Server
22.06 12:25:26 [Multicraft] Server shut down (stopping)
22.06 12:25:26 [Multicraft] Server stopped
22.06 12:25:30 [Multicraft] Loading server properties
22.06 12:25:30 [Multicraft] Loaded config for "Paper"
22.06 12:25:30 [Multicraft] Starting server!
22.06 12:25:31 [Multicraft] Adding template "apexupdater" and options "always,install,temp" from config
22.06 12:25:31 [Multicraft] Running setup...
22.06 12:25:32 [Setup/"Apex Updater" initialize] Running Apex Updater...
22.06 12:25:32 [Setup/"Apex Updater" initialize] Selected JAR = paper_1.20.1
22.06 12:25:32 [Multicraft] Done, returned Ok
22.06 12:25:32 [Multicraft] Setup done, restarting
22.06 12:25:32 [Multicraft] Server stopped
22.06 12:25:35 [Multicraft] Loading server properties
22.06 12:25:35 [Multicraft] Loaded config for "Paper"
22.06 12:25:35 [Multicraft] Starting server!
22.06 12:25:36 [Multicraft] Updating eula.txt file
22.06 12:25:36 [Server] INFO WARNING: Published ports are discarded when using host network mode
22.06 12:25:36 [Server] INFO 0e518b7a18e6af595c877a23ae77fecf73e43d3cf1137f90bc663e8ae707fb33
22.06 12:25:38 [Server] INFO Starting org.bukkit.craftbukkit.Main
22.06 12:25:38 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
22.06 12:25:38 [Server] INFO [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
22.06 12:25:38 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
22.06 12:25:38 [Server] INFO System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 4.18.0-305.19.1.el8_4.x86_64 (amd64)
22.06 12:25:38 [Server] INFO Loading libraries, please wait...
22.06 12:25:38 [Server] INFO 2023-06-22 12:25:38,997 ServerMain WARN Advanced terminal features are not available in this environment
22.06 12:25:43 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
22.06 12:25:44 [Server] INFO Loaded 7 recipes
22.06 12:25:45 [Server] INFO Starting minecraft server version 1.20.1
22.06 12:25:45 [Server] INFO Loading properties
22.06 12:25:45 [Server] INFO This server is running Paper version git-Paper-45 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b169678)
22.06 12:25:45 [Server] INFO Server Ping Player Sample Count: 12
22.06 12:25:45 [Server] INFO Using 4 threads for Netty based IO
22.06 12:25:45 [Server] WARN [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
22.06 12:25:45 [Server] INFO We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
22.06 12:25:45 [Server] INFO For more information please visit: https://github.com/PaperMC/Paper/issues/8948
22.06 12:25:45 [Server] INFO [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
22.06 12:25:45 [Server] INFO Default game type: SURVIVAL
22.06 12:25:45 [Server] INFO Generating keypair
22.06 12:25:45 [Server] INFO Starting Minecraft server on
22.06 12:25:46 [Server] INFO Using epoll channel type
22.06 12:25:46 [Server] INFO Paper: Using libdeflate (Linux x86_64) compression from Velocity.
22.06 12:25:46 [Server] INFO Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
22.06 12:25:46 [Server] INFO [Multiverse-Core] Loading server plugin Multiverse-Core v4.3.1-b861
22.06 12:25:46 [Server] INFO [Multiverse-Portals] Loading server plugin Multiverse-Portals v4.2.1-b834
22.06 12:25:46 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
22.06 12:25:46 [Server] INFO Preparing level "testing"
22.06 12:25:47 [Server] INFO Preparing start region for dimension minecraft:overworld
22.06 12:25:47 [Server] INFO Time elapsed: 312 ms
22.06 12:25:47 [Server] INFO Preparing start region for dimension minecraft:the_nether
22.06 12:25:47 [Server] INFO Time elapsed: 105 ms
22.06 12:25:47 [Server] INFO Preparing start region for dimension minecraft:the_end
22.06 12:25:47 [Server] INFO Time elapsed: 94 ms
22.06 12:25:48 [Server] INFO [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
22.06 12:25:48 [Server] WARN [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
22.06 12:25:48 [Server] INFO [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
22.06 12:25:48 [Server] INFO [Multiverse-Core] 3 - World(s) loaded.
22.06 12:25:48 [Server] WARN [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
22.06 12:25:48 [Server] INFO [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
22.06 12:25:48 [Server] INFO [Multiverse-Portals] Enabling Multiverse-Portals v4.2.1-b834
22.06 12:25:48 [Server] INFO [Multiverse-Portals] 0 - Portals(s) loaded
22.06 12:25:48 [Server] INFO [Multiverse-Portals 4.2.1-b834]  Enabled - By Rigby and fernferret
22.06 12:25:48 [Server] INFO Running delayed init tasks
22.06 12:25:48 [Server] Startup Done (3.476s)! For help, type "help"
22.06 12:25:48 [Server] INFO Timings Reset
22.06 12:26:03 [Server] INFO CollaboK8 joined the game
22.06 12:26:04 [Multicraft] CollaboK8 ran command Message of the Day
22.06 12:26:10 [Server] INFO CollaboK8 issued server command: /gamemode creative
22.06 12:26:10 [Server] INFO [CollaboK8: Set own game mode to Creative Mode]
22.06 12:26:20 [Server] INFO CollaboK8 issued server command: /mv create world1
22.06 12:26:36 [Server] INFO CollaboK8 issued server command: /mv create world normal -t flat
22.06 12:26:36 [Server] INFO CollaboK8: Starting creation of world 'world'...
22.06 12:26:36 [Server] INFO [Multiverse-Core] Loading World & Settings - 'world' - Env: NORMAL - Type: FLAT
22.06 12:26:36 [Server] ERROR No key layers in MapLike[{}]
22.06 12:26:36 [Server] INFO Preparing start region for dimension minecraft:world
22.06 12:26:36 [Server] INFO Time elapsed: 112 ms
22.06 12:26:36 [Server] INFO CollaboK8: Complete!
22.06 12:26:39 [Server] INFO CollaboK8 issued server command: /mv list
22.06 12:26:45 [Server] INFO CollaboK8 issued server command: /mv tp world
22.06 12:26:51 [Server] INFO CollaboK8 issued server command: /difficulty peaceful
22.06 12:26:51 [Server] INFO [CollaboK8: The difficulty has been set to Peaceful]
22.06 12:26:58 [Server] INFO CollaboK8 issued server command: /gamemode creative
22.06 12:26:58 [Server] INFO [CollaboK8: Set own game mode to Creative Mode]
22.06 12:27:26 [Server] INFO CollaboK8 issued server command: /mv wand
22.06 12:27:32 [Server] INFO CollaboK8 issued server command: /mvp wand
22.06 12:27:41 [Server] INFO CollaboK8 issued server command: /mvp create portal1
22.06 12:27:48 [Server] INFO CollaboK8 issued server command: /mv tp testing
22.06 12:27:54 [Server] INFO CollaboK8 issued server command: /gamemode creative
22.06 12:27:54 [Server] INFO [CollaboK8: Set own game mode to Creative Mode]
22.06 12:28:16 [Server] INFO CollaboK8 issued server command: /mvp create portal2
22.06 12:29:17 [Server] INFO CollaboK8 issued server command: /mv tp world
22.06 12:29:25 [Server] INFO CollaboK8 issued server command: /mvp select portal1
22.06 12:29:36 [Server] INFO CollaboK8 issued server command: /mvp modify dest p:portal2
22.06 12:29:48 [Server] INFO CollaboK8 issued server command: /mv tp testing
22.06 12:29:55 [Server] INFO CollaboK8 issued server command: /mvp select portal2
22.06 12:30:07 [Server] INFO CollaboK8 issued server command: /mvp modify dest p:portal1
22.06 12:30:17 [Disconnect] User CollaboK8 has disconnected, reason: Disconnected
22.06 12:30:17 [Server] INFO CollaboK8 left the game
22.06 12:30:54 [Multicraft] Received restart command
22.06 12:30:54 [Multicraft] Stopping server!
22.06 12:30:54 [Server] INFO Saving the game (this may take a moment!)
22.06 12:30:54 [Server] INFO Saved the game
22.06 12:30:54 [Server] INFO Stopping the server
22.06 12:30:54 [Server] INFO Stopping server
22.06 12:30:54 [Server] INFO [Multiverse-Portals] Disabling Multiverse-Portals v4.2.1-b834
22.06 12:30:54 [Server] INFO [Multiverse-Core] Disabling Multiverse-Core v4.3.1-b861
22.06 12:30:54 [Server] INFO Saving players
22.06 12:30:54 [Server] INFO Saving worlds
22.06 12:30:54 [Server] INFO Saving chunks for level 'ServerLevel[testing]'/minecraft:overworld
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saved 0 block chunks, 101 entity chunks, 0 poi chunks in world 'testing' in 0.01s
22.06 12:30:54 [Server] INFO ThreadedAnvilChunkStorage (testing): All chunks are saved
22.06 12:30:54 [Server] INFO Saving chunks for level 'ServerLevel[testing_nether]'/minecraft:the_nether
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing_nether'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing_nether'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing_nether'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saved 0 block chunks, 24 entity chunks, 0 poi chunks in world 'testing_nether' in 0.00s
22.06 12:30:54 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
22.06 12:30:54 [Server] INFO Saving chunks for level 'ServerLevel[testing_the_end]'/minecraft:the_end
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'testing_the_end'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'testing_the_end'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'testing_the_end'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saved 0 block chunks, 10 entity chunks, 0 poi chunks in world 'testing_the_end' in 0.00s
22.06 12:30:54 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
22.06 12:30:54 [Server] INFO Saving chunks for level 'ServerLevel[world]'/minecraft:world
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Halted chunk system for world 'world'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saving all chunkholders for world 'world'
22.06 12:30:54 [Server] INFO [ChunkHolderManager] Saved 1534 block chunks, 6 entity chunks, 0 poi chunks in world 'world' in 0.45s
22.06 12:30:54 [Server] INFO ThreadedAnvilChunkStorage (world): All chunks are saved
22.06 12:30:54 [Server] INFO ThreadedAnvilChunkStorage: All dimensions are saved
22.06 12:30:54 [Server] INFO Flushing Chunk IO
22.06 12:30:54 [Server] INFO Closing Thread Pool
22.06 12:30:54 [Server] INFO 2023-06-22 12:30:54,902 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
22.06 12:30:54 [Server] INFO Closing Server
22.06 12:30:56 [Multicraft] Server shut down (stopping)
22.06 12:30:56 [Multicraft] Server stopped
22.06 12:30:59 [Multicraft] Loading server properties
22.06 12:30:59 [Multicraft] Loaded config for "Paper"
22.06 12:30:59 [Multicraft] Starting server!
22.06 12:31:00 [Multicraft] Adding template "apexupdater" and options "always,install,temp" from config
22.06 12:31:00 [Multicraft] Running setup...
22.06 12:31:01 [Setup/"Apex Updater" initialize] Running Apex Updater...
22.06 12:31:01 [Setup/"Apex Updater" initialize] Selected JAR = paper_1.20.1
22.06 12:31:01 [Multicraft] Done, returned Ok
22.06 12:31:01 [Multicraft] Setup done, restarting
22.06 12:31:01 [Multicraft] Server stopped
22.06 12:31:05 [Multicraft] Loading server properties
22.06 12:31:05 [Multicraft] Loaded config for "Paper"
22.06 12:31:05 [Multicraft] Starting server!
22.06 12:31:06 [Multicraft] Updating eula.txt file
22.06 12:31:06 [Server] INFO WARNING: Published ports are discarded when using host network mode
22.06 12:31:06 [Server] INFO 04b1d0cd0c77796644e48bc064cad8299e3e6720dd2d3c518e18b452ad565265
22.06 12:31:08 [Server] INFO Starting org.bukkit.craftbukkit.Main
22.06 12:31:08 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
22.06 12:31:08 [Server] INFO [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
22.06 12:31:08 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
22.06 12:31:08 [Server] INFO System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.7+7) Host: Linux 4.18.0-305.19.1.el8_4.x86_64 (amd64)
22.06 12:31:08 [Server] INFO Loading libraries, please wait...
22.06 12:31:08 [Server] INFO 2023-06-22 12:31:08,715 ServerMain WARN Advanced terminal features are not available in this environment
22.06 12:31:12 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
22.06 12:31:14 [Server] INFO Loaded 7 recipes
22.06 12:31:14 [Server] INFO Starting minecraft server version 1.20.1
22.06 12:31:14 [Server] INFO Loading properties
22.06 12:31:14 [Server] INFO This server is running Paper version git-Paper-45 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b169678)
22.06 12:31:15 [Server] INFO Server Ping Player Sample Count: 12
22.06 12:31:15 [Server] INFO Using 4 threads for Netty based IO
22.06 12:31:15 [Server] WARN [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
22.06 12:31:15 [Server] INFO We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
22.06 12:31:15 [Server] INFO For more information please visit: https://github.com/PaperMC/Paper/issues/8948
22.06 12:31:15 [Server] INFO [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
22.06 12:31:15 [Server] INFO Default game type: SURVIVAL
22.06 12:31:15 [Server] INFO Generating keypair
22.06 12:31:15 [Server] INFO Using epoll channel type
22.06 12:31:15 [Server] INFO Paper: Using libdeflate (Linux x86_64) compression from Velocity.
22.06 12:31:15 [Server] INFO Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
22.06 12:31:16 [Server] INFO [Multiverse-Core] Loading server plugin Multiverse-Core v4.3.1-b861
22.06 12:31:16 [Server] INFO [Multiverse-Portals] Loading server plugin Multiverse-Portals v4.2.1-b834
22.06 12:31:16 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
22.06 12:31:16 [Server] INFO Preparing level "testing"
22.06 12:31:17 [Server] INFO Preparing start region for dimension minecraft:overworld
22.06 12:31:17 [Server] INFO Time elapsed: 388 ms
22.06 12:31:17 [Server] INFO Preparing start region for dimension minecraft:the_nether
22.06 12:31:17 [Server] INFO Time elapsed: 96 ms
22.06 12:31:17 [Server] INFO Preparing start region for dimension minecraft:the_end
22.06 12:31:17 [Server] INFO Time elapsed: 23 ms
22.06 12:31:17 [Server] INFO [Multiverse-Core] Enabling Multiverse-Core v4.3.1-b861
22.06 12:31:17 [Server] WARN [Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
22.06 12:31:17 [Server] INFO [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
22.06 12:31:18 [Server] INFO Preparing start region for dimension minecraft:world
22.06 12:31:18 [Server] INFO Time elapsed: 88 ms
22.06 12:31:18 [Server] INFO [Multiverse-Core] 4 - World(s) loaded.
22.06 12:31:18 [Server] WARN [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.
22.06 12:31:18 [Server] INFO [Multiverse-Core] Version 4.3.1-b861 (API v24) Enabled - By dumptruckman, Rigby, fernferret, lithium3141 and main--
22.06 12:31:18 [Server] INFO [Multiverse-Portals] Enabling Multiverse-Portals v4.2.1-b834
22.06 12:31:18 [Server] INFO [Multiverse-Portals] 2 - Portals(s) loaded
22.06 12:31:18 [Server] INFO [Multiverse-Portals 4.2.1-b834]  Enabled - By Rigby and fernferret
22.06 12:31:18 [Server] INFO Running delayed init tasks
22.06 12:31:18 [Server] Startup Done (3.535s)! For help, type "help"
22.06 12:31:18 [Server] INFO Timings Reset

**Comment by IniTrid** [comment]
I hope a 1.20.1 version will come soon, I've got the same problem

**Comment by zax71** [comment]
I cannot reproduce this issue on Paper 1.20.1 V47 with WorldEdit, MVP and MV installed

**Comment by NoChillFM** [comment]
Having this issue with latest version of papermc with MV Core, Portals, and Inventories. Inventories is stable, but Portal and Core are unusable, I receive a internal command error.
