### ISSUE TITLE
Players can't access portals

### ISSUE THREAD

**Issue by wavywonderz** [Multiverse/Multiverse-Portals#98]
I'm Trying to make a portal to the nether at the spawn. I want to enforce the access of the portal so only people who passed a test can enter, but not everyone. I also do not want the who passed the test to be ops. I give the people who passed the test:

`multiverse.portal.access.PORTALNAME` (to nether)
`multiverse.portal.access.PORTALNAME` (from nether)

and

`multiverse.access.NETHERWORLDNAME`

but they still can't access it if i have the enforce access for worlds and portals on. There is no portal block in the portal, it is just a rectangle portal thing with nothing in the inside

**Comment by FernFerret** [comment]
Closing as inactive (> 7 days without comment from submitter) and we're trying to keep up with idle issues better.

If you're still having issues, please post an update and we'll reopen this!  :+1:

**Comment by Climberirw** [comment]
type `/mvp config enforceportalaccess false` into the Minecraft chat on your server.
